### ISSUE TITLE
What insitution currently support MFA?

### ISSUE THREAD

**Issue by kopachevsky** [plaid/support#100]
I'm currently testing Plaid API and have in mind to use it, but I can't find bank that currently support MFA to test API with. Sure I saw page:
https://plaid.com/docs/#institutions
I've tried my Bank of America account, and Plaid didn't ask for any MFA - login and password was enought, so before I'll create account in other bank for testing, please provide bank name that WILL ask for MFA.
Thanks.

**Comment by kopachevsky** [comment]
Here is request example:

curl -X POST https://api.plaid.com/auth \
  -d client_id=xxxxx \
  -d secret=xxxxxxx \
  -d username=xxxx \
  -d password=xxxxxx \
  -d type=bofa \
  -d options='{"list":true}'

Response:

  {
  "accounts": [
    {
      "_id": "xxxx",
      "numbers": {
        "account": "xxxx",
        "routing": "xxxx",
        "wireRouting": "xxxxx"
      },
      "meta": {
        "official_name": "BofA Core Checking",
        "number": "2054",
        "name": "BofA Core Checking",
        "limit": null
      },
      "balance": {
        "available": 1,
        "current": 1
      },
      "type": "depository",
      "institution_type": "bofa",
      "_user": "xxxxxx",
      "_item": "xxxxxx"
    }
  ],"access_token": "xxxxxxxxx"

**Comment by ctrembl** [comment]
This is a result of Plaid actively working to reduce the MFA requirements for users at the financial institutions we support. As such, we recommend building your integration with the expectation that MFA is always a possibility, but not always required.

Let us know if you have any additional questions!
