### ISSUE TITLE
Removing orphaned accounts without knowing the plaid_token.

### ISSUE THREAD

**Issue by dam13n** [plaid/support#101]
Would be cool to have a feature that addressed this! We are live, but there are have been bugs and some of the testing we have to do live because not all features are on the test environment.

I brought up this up a while ago, and I remember hearing that security was a concern for a feature like this ( a method that say, returns all plaid_tokens), which makes sense.

What about a feature where we could submit all plaid_tokens we DIDN'T want removed and then the rest were purged. Perhaps that could require a confirmation and some meta data for us to make sure we want to do it (number of accounts to be removed and whatever else).

**Comment by pgorsira** [comment]
Yea this would be great

**Comment by michaelckelly** [comment]
Hi Damien & Pieter-

Thanks for the feedback - I'll pass it along to team.  Plaid's general recommendation is to store the access token for each account your create somewhere secure & durable (i.e. a database or file).  Currently, getting in touch with support@plaid.com is the best way to sort something like this out.

On another note, we recently rolled out support for options (filtering by account & date) on the sandbox for connect requests (example below).   
```  
curl -X POST https://tartan.plaid.com/connect/get \
  -d client_id=test_id \
  -d secret=test_secret \
  -d access_token=test \
  -d options='{"account":"pJPM4LMBNQFrOwp0jqEyTwyxJQrQbgU6kq37k","gte":"2014-04-17"}' \
  -d type=chase
```
