### ISSUE TITLE
Real bank accounts in the Sandbox

### ISSUE THREAD

**Issue by garrettlangley** [plaid/support#103]
When trying to use real bank accounts in the sandbox, I get the following error:

"code": 1610,
  "message": "item not found",
  "resolve": "No matching items found; go add an account!"

What am I doing wrong?

**Comment by ctrembl** [comment]
Hey @garrettlangley - if you could send us more information about the query you're making to support@plaid.com, we'll be sure to take a closer look! Please don't include any sensitive information like your secret or online banking credentials.
