### ISSUE TITLE
Account Types

### ISSUE THREAD

**Issue by pski** [plaid/support#104]
The link to account types in the Data Overview section on the main documentation site is broken.

That being said, what are the account type codes?  

I found https://github.com/plaid/support/blob/master/accounts-supported.md.

Do you supply account subtypes?  We need to distinguish between checking and savings.

Thanks!

**Comment by ctrembl** [comment]
Hey Pete - Thanks for catching this! We'll get a fix up for it shortly.

In the meantime, the account type codes you can expect to see are: `Depository`, `Credit`, `Loan`, `Mortgage`, `Brokerage`, and `Other`.

We also provide subtypes when applicable (and available), the most common being `Checking` and `Savings`.
