### ISSUE TITLE
No availability for Silicon Valley Bank

### ISSUE THREAD

**Issue by seanmccann** [plaid/support#105]
Plaid added SVB but there is no availability data noted anywhere.

**Comment by michaelckelly** [comment]
Hi @seanmccann:

SVB is currently only available on tartan (our development environment) and is still in the early stages of our integration.  We will update our docs and support resources once it is production ready!

**Comment by seanmccann** [comment]
@michaelckelly SVB is showing up as an institution on `https://api.plaid.com/institutions`. I assumed that institutions listed at that endpoint were live. If this is not the case, I'll probably need to make some changed to our implementation.

**Comment by michaelckelly** [comment]
@seanmccann Thanks for pointing that out - that was misleading on our part.  `https://api.plaid.com/institutions` no longer lists SVB or PNC as supported institutions.  Attempting to add a SVB or PNC account on the production API will result in a `code 1300 / institution not available` error, which I hope is much clearer than the `planned maintenance` error we previously returned.

`https://tartan.plaid.com/institutions` correctly lists support SVB and PNC.

Hopefully that means you can keep your implementation the same.  The `/institutions` endpoint is designed to be the authoritative source for the institutions supported in a given environment.

Thanks for bringing this up.

**Comment by seanmccann** [comment]
@michaelckelly Thanks so much!

**Comment by yankit007** [comment]
@michaelckelly  I am trying to implement Plaid Api but when i have used PNC bank, it is showing error " products not available". i unable to get response. so what is problem in PNC bank ? Please let me know..
Thanks in Advance

**Comment by robmpreston** [comment]
Im getting 'products not available' for Plaid API using PNC Bank with Connect in Tartan, but it looks like this should work according to the institutions list. Can you confirm @michaelckelly
