### ISSUE TITLE
Link on website

### ISSUE THREAD

**Issue by c316** [plaid/support#107]
https://plaid.com/docs/#data-overview
Inside the Account data elements table at the bottom the link for type: goes here https://plaid.com/docs/expand#connect-account-types, but that doesn't seem to exist.

**Comment by c316** [comment]
I ran this link checker for you, might help with finding all the bad links, and other things to fix. 

http://validator.w3.org/checklink?uri=https%3A%2F%2Fplaid.com%2Fdocs%2F&hide_type=all&depth=&check=Check

**Comment by michaelckelly** [comment]
@c316 Thanks for pointing that out - we'll get that fixed shortly!
