### ISSUE TITLE
Webhook on PATCH

### ISSUE THREAD

**Issue by pski** [plaid/support#109]
Please explain the behavior of transaction retrieval on a PATCH /connect to update an existing user's credentials.  Will the webhook for the access_token get invoked?  I do see the PATCH call will also synchronously return transactions.  

I'm thinking of what happens if a user updates his credentials in plaid after 2 or 3 or even 6 months after changing them with the bank.  How can I be sure to have his complete set of transactions without any gaps?  

Thanks.

**Comment by ctrembl** [comment]
Hey @pski , apologies for the delayed response here!

If a PATCH request to `/connect` is run after a user has been inactive/invalidated for an extended period of time, Plaid will still retrieve transactions from as far back as they are available. That said, if the user is from a bank where transactions are only available going 3 months back and the user has been invalidated for 6, then there will be a gap in transactions.

Once these transactions have been retrieved, Plaid will trigger webhooks to notify you that the transactions are now available (as long as a webhook address is associated with the access_token).
