### ISSUE TITLE
Hitting /connect/get to retrieve transactions, triggering "Type paramater" issue

### ISSUE THREAD

**Issue by parchambeau** [plaid/support#112]
I am getting back the error "You need to include a type parameter. Ex. bofa, wells, amex, chase, citi, etc." when attempting to hit the /connect/get endpoint.

Looking at the documentation it does not seem like we should need to pass the type parameter for this call. Has something changed and the documentation is not updated?

**Comment by michaelckelly** [comment]
@parchambeau 

What type of request are you making -- i.e. a request with a live access token or to our testing/sandbox environment?

Michael

**Comment by parchambeau** [comment]
They are sandbox accounts on api.plaid.com

**Comment by michaelckelly** [comment]
Mind sharing the exact request?  That'll help us debug it a bit quicker.

We did release an update to our sandbox earlier today (updated docs are live at https://plaid.com/docs/#sandbox) but no existing functionality should have been broken.

Michael

**Comment by parchambeau** [comment]
Below is the request:

curl -X POST https://api.plaid.com/connect/get \
 -d client_id=<our client id> \
 -d secret=<our client secret> \
 -d access_token=test

{
 "code": 1001,
 "message": "type missing",
 "resolve": "You need to include a type parameter. Ex. bofa, wells, amex, chase, citi, etc.",
 "access_token": "test"
}

**Comment by michaelckelly** [comment]
@parchambeau 

For sandbox requests that use `test` as the access token a `type` parameter is required - that allows us to better replicate the flow for each distinct institution in the sandbox.  This was a bit of a cumbersome experience, though, so we've updated our sandbox to no longer require that parameter.  Instead, the access token is in the format `test_{TYPE}`, i.e. `test_amex` or `test_chase`.

Here's a sample request
```
curl -X POST https://api.plaid.com/connect/get \
-d client_id=test_id \
-d secret=test_secret \
-d access_token=test_chase
```
