### ISSUE TITLE
Balance Refresh Schedule

### ISSUE THREAD

**Issue by paragp90** [plaid/support#113]
Hi, we're looking at using Plaid for supplying data to one of our products. We need daily account balance updates (during the morning before 11 am) for one of our features. 

How can we ensure that the balance information we have for users is up-to-date?

Additionally, I would like to know:
1. what is the refresh schedule for real time balance and latency/gap between each refresh?
2. we understand that Plaid pushes new transaction data every time it refreshes (every 4 hours), does this include real time balance? Since there is a separate API for balance.

**Comment by ctrembl** [comment]
Hi @paragp90 - balance information will be updated according to the product(s) being utilized for a particular access token.

__Balance:__ When using the `/balance` endpoint, balance information is retrieved real time and has a maximum latency of a few seconds.

__Connect:__ With the `/connect` product, balance information - along with all other account and transaction information - is updated every 4 to 6 hours. If the `/balance` endpoint is utilized on an access token that is currently active on `/connect`, the balances will be updated accordingly but a full transaction retrieval will not occur.

Don't hesitate to reach out if you have any other questions!

**Comment by aatreya** [comment]
Are there any plans to allow on-demand data refreshes for the /connect endpoint?
