### ISSUE TITLE
Not showing pending transactions

### ISSUE THREAD

**Issue by paulshen** [plaid/support#114]
I've been using the Plaid Node API and it doesn't seem to get pending transactions (testing on Chase credit card transactions).

```javascript
plaid.get(access_token, {pending: true}, function(err, result) {
  ...
});
```

I believe this used to work a while ago but now, I seem to only get transactions that are more than a week old (while more recent transactions show up in Mint / Chase website). No transactions show up that are marked as pending. Thanks!

**Comment by ctrembl** [comment]
Hey @paulshen  - If you could send this information and the affected access_token over to support@plaid.com, we'll take a closer look! Thanks.
