### ISSUE TITLE
plaid_selections giving invalid credentials 

### ISSUE THREAD

**Issue by pgorsira** [plaid/support#115]
My request:

    curl -X POST https://tartan.plaid.com/connect \
      -d client_id=test_id \
      -d secret=test_secret \
      -d username=plaid_selections \
      -d password=plaid_good \
      -d type=wells

Response:

    {
      "code": 1200,
      "message": "invalid credentials",
      "resolve": "The username or password provided were not correct."
    }

**Comment by ctrembl** [comment]
Currently, selection-based MFA is only applicable to certain financial institutions. You can see an up-to-date list of which institutions [here](https://plaid.com/docs/#institutions) - I believe it is just Citi at the moment.

This particular call with `type=citi` should go through just fine. All other institutions however will error.
