### ISSUE TITLE
Some posted transactions do not have references to their _pendingTransaction

### ISSUE THREAD

**Issue by pgorsira** [plaid/support#116]
Hey guys,

Seeing an issue where some users have duplicate transactions in our app. Went through some logs to figure things out, and here's what I think is happening:

1. We request transactions from you guys (with pending: true) and receive some pending transactions. These are persisted to our db with the *_id* given (which as I understand it is kind of a "temporary id" for pending transactions as they eventually make their way to a posted status).

2. A few days later, we request transactions from you guys (once again with pending: true). The original pending transaction *_id*s from before are not present in this response (which is to be expected I believe once the transactions are posted). However, these same transactions (the ones that were pending) **are** returned as posted transactions (that is, they have the same name/price/location/etc as the original pending ones, but now have their pending attribute assigned to false, and they have different *_id* attributes). However, these posted transactions in this response **do not** have *_pendingTransaction* attributes that link back to their original pending transaction *_id*.

So, what ends up happening is that our system sees what is actually just one transaction in the user's bank account as 2 distinct transactions (once when it's a pending state, and once in a posted state). Due to the posted transactions not having a *_pendingTransaction* attribute, our system is unable to link the 2 transactions.

Currently, this issue is only verified as affecting one of our Chase customers (not sure if other institutions have this issue).

**Comment by benperez** [comment]
Hey,

I'd be more than happy to take a look at this particular account, would you mind sending the affected account/transaction ID's over to support@plaid.com so I can take a closer look?

Thanks,
Ben

**Comment by pgorsira** [comment]
Cool, email sent
