### ISSUE TITLE
Does Plaid support this Chase Card?

### ISSUE THREAD

**Issue by parchambeau** [plaid/support#117]
Hey guys,

We have a customer who is receiving the error message **"The institution is failing to respond to our request, if you resubmit the query the request may go through."** when attempting to log into his Chase account(He only has a Credit Card with them). We have spoken to him and asked what type of Chase credit card he is using and he told us that he is using the "Chase Amazon Visa" (Link to Card below). 

https://www.chase.com/credit-cards/amazon/amazon-home

This seems to be some sort of Amazon specific rewards card, so I am not sure if this falls under the "Chase" cards that you support. 

Thank you for your help

**Comment by parchambeau** [comment]
Bump.

**Comment by ctrembl** [comment]
Hey @parchambeau - apologies for the delayed response!

Plaid supports all credit cards at Chase including the Chase Amazon Visa. If you could send over the access token to support@plaid.com with a brief description of the issue, our team will take a closer look and get back to you shortly.

**Comment by parchambeau** [comment]
Hey @ctrembl just sent support an email to follow up, thanks for the help.
