### ISSUE TITLE
Sandbox : example with phone number and foursquare ID

### ISSUE THREAD

**Issue by dmichiels** [plaid/support#118]
Hello,

Using the sandbox and the documentation, I can't find any example of the metadata "contact" and "ids", respectively the phone number and the Foursquare ID. 
That would be great to have them in at least one sandbox transaction to make tests.

Is that possible?
Best regards,

**Comment by zperret** [comment]
Great idea. We'll add this to the list of additional features to consider when we re-work the sandbox next.
