### ISSUE TITLE
Pending transactions?

### ISSUE THREAD

**Issue by mackermedia** [plaid/support#122]
I've successfully been able to see transactions using the 'connect' API type (however not with the 'auth' type), but I seem to only be seeing non-pending transactions.

I'd like to be able to get pending transactions so that my application can give users updated transaction information in near real-time, rather than up to a few days late.

My card type is 'citi'.

I saw issue #114 which suggests that at some point (perhaps even now?) pending transactions are working for the node.js library. I'm using the ruby library. 

Any suggestions?

**Comment by hosh** [comment]
@mackermedia hey, I've been having the same trouble with the Ruby library. I've been submitting a lot of PRs, and working on a PR that lets you pass options against the `/connect/get` endpoint.

Unfortunately, this is what I am running into:

```
curl -X POST https://tartan.plaid.com/connect/get \
  -d client_id=${PLAID_ID} \
  -d secret=${PLAID_SECRET} \
  -d access_token=test_wells \
  -d options='{"account": "QPO8Jo8vdDHMepg41PBwckXm4KdK1yUdmXOwK"}'
```

At least for the test data, it doesn't filter it.

If you can get something like this working for your test data, let me know. I'll be adding a `Plaid.transactions` method that lets you pass options like `pending` or `account`.

**Comment by hosh** [comment]
Ok, I see what's going on: the `account` filter will filter the transactions but not the account. Not ideal but good enough for now.

I'm going to go ahead and finish this for the Ruby client. The maintainer is usually pretty fast about merging those changes in.

**Comment by hosh** [comment]
@mackermedia https://github.com/plaid/plaid-ruby/pull/47

**Comment by mackermedia** [comment]
@hosh Awesome! This is great! I tested it out and I'm now seeing pending transactions.

Thanks so much! :+1:

**Comment by hosh** [comment]
:+1:

**Comment by zperret** [comment]
Thanks @hosh! Looks like we're good here. Closing now...

**Comment by ufdeveloper** [comment]
I am not able to get pending transactions using the public API. I tried to add "pending":true to the options parameter to the /connect/get endpoint, but still no use.
