### ISSUE TITLE
BofA stops asking MFA questions too early

### ISSUE THREAD

**Issue by pgorsira** [plaid/support#124]
Have seen this with 2 of our users. The user logs into BofA and we send that info to Plaid. Plaid indicates that there is MFA required. User completes MFA. Plaid indicates there is no more MFA. Attempt to list accounts for user by hitting `/auth/get`. Plaid gives the following response:

    {
      "code": 1215,
      "message": "mfa reset",
      "resolve": "MFA access has changed or this application's access has been revoked. Submit a PATCH call to resolve.",
      "access_token": "<user's access token>" 
    }

Why did Plaid stop asking MFA questions? Technically, we could handle this situation, but to do it elegantly would require some persistence of user bank login credentials (which is also bad) - we can't ask the user to re-login right after they just logged in. Instead, it seems like "MFA access" should not change right after onboarding a user into Plaid. Correct me if I'm wrong, but it seems like the idea is to get all of the MFA out of the way right away.

Can provide access tokens upon request.

**Comment by ctrembl** [comment]
@pgorsira, would you mind sending over the access tokens to support@plaid.com?

We'll take a closer look and get back to you shortly. Thanks!

**Comment by pgorsira** [comment]
False alarm

**Comment by ctrembl** [comment]
Got it, thanks for the update @pgorsira

**Comment by rubysolo** [comment]
@pgorsira We're seeing a similar message, but with US Bank rather than BofA.  Can you share what the cause / fix was in your case?

**Comment by unp** [comment]
@pgorsira I'm also seeing the same message with a Chase user. Would love to know what caused the error on your end.

**Comment by michaelckelly** [comment]
@unp @rubysolo 

Happy to look into both of these issue - please shoot us a note at support@plaid.com with the affected access token!

**Comment by rubysolo** [comment]
@michaelckelly @unp We were seeing this with a user that had not yet completed the MFA flow.  See notes here for our workaround: https://github.com/plaid/plaid-ruby/pull/89
