### ISSUE TITLE
[Question] Is selection-based MFA always answered with an array?

### ISSUE THREAD

**Issue by pgorsira** [plaid/support#125]
This one may be an issue on our end, so just want to clarify something. 

From the docs (emphasis mine):

> Selection-Based MFA

> Some institutions require the user to answer a question from a limited set of answers, i.e. multiple-choice. Multiple questions may be returned, and the **MFA answer submission must be a JSON-encoded array with answers** provided in the same order as the given questions.

What about in the case of selection-based MFA with only one question (and consequently only one answer)? Right now our issue is that users are getting *The MFA response provided was not correct* when answering such questions, and their answers are wrapped in an array. Example:

MFA proposal received from Plaid:

    [
        {
            'answers': ['Northern', 'Southern'],
            'question': "Did you open account 'Basic Checking: 522' in Northern  California (including San Francisco & Central California) or Southern California (including Los Angeles and San Diego)?"
        }
    ]

What we send to Plaid after the user responds:
    
    {
        'client_id': xxxx,
        'secret': xxxx,
        'access_token': xxxx,
        'type': 'citi',
        'mfa': ['Southern']
    }

Which gets the *incorrect MFA* error above. So, my question is, in this case, should our "answering" request look like this:
    
    {
        'client_id': xxxx,
        'secret': xxxx,
        'access_token': xxxx,
        'type': 'citi',
        'mfa': 'Southern'
    }

i.e., not wrapped in an array.

Unfortunately plaid_selections seems to give back 2 questions so I couldn't test this with that, and the other dev here who has Citi wasn't asked for MFA. So, I have no way of verifying whether or not this could be the root of the issue. Hope you guys can shed some light on the situation. Thanks.

**Comment by pgorsira** [comment]
bump

**Comment by ctrembl** [comment]
Answers to selection-based MFA should always be in the form of an array. This is true regardless of the number of questions being asked, which may be one or two.
