### ISSUE TITLE
pending transactions missing meta data

### ISSUE THREAD

**Issue by garrettlangley** [plaid/support#126]
is it expected that pending transactions will lack meta data such as location and categories?

**Comment by garrettlangley** [comment]
@davidchambers any chance you could help out? have a few open requests atm

**Comment by zperret** [comment]
Yes, pending transactions often have less data than posted transactions. While we do our best to clean up all transactions and add locations, categories, etc., all this depends depends on the quality of the data we start with. Unfortunately, pending transactions often have less data than posted ones.
