### ISSUE TITLE
Customer claims that SafePass is disabled on BoA account yet still receives "account not supported"

### ISSUE THREAD

**Issue by pgorsira** [plaid/support#132]
Hey guys, 

As the title says, one of our users is receiving error code 1210 (account not supported) upon logging into their BoA account. I suggested he disable SafePass; however, he replied saying that SafePass has been disabled on his account for a few weeks. 

I've instructed him to attempt logging in again and make note of the time he does so. Can you guys take a look on your side once I have this info and see what's up?

**Comment by susanfowler** [comment]
Hi @pgorsira!

When you have the info, send it to support@plaid.com - we'll take a look and figure out what's going on.

**Comment by pgorsira** [comment]
Welp, he tried logging in again at 04/18/15 6:35PM PT but it went through this time. Not sure what the issue was.
