### ISSUE TITLE
Institution type

### ISSUE THREAD

**Issue by c316** [plaid/support#133]
I'm planning my data schema. I'm planning to store all of the accounts in a single collection (MongoDB) and associate these accounts based on the _user used and my own app's user collection. 

Will the institution_type be the same for all of the sub-accounts under one bank account? I noticed the _user test data was the same for different institutions, or I'd use that. 

Thanks

**Comment by ctrembl** [comment]
Instead of using _user, I would recommend using the _item id for association purposes. The _item id will be consistent across all of the accounts associated with a particular access token.

And yes, the institution _type will be the same for all accounts associated with a particular access token / _item.

**Comment by c316** [comment]
Thanks, will do

On Fri, Apr 17, 2015 at 8:24 PM, Carl <notifications@github.com> wrote:

> Instead of using _user, I would recommend using the _item id for
> association purposes. The _item id will be consistent across all of the
> accounts associated with a particular access token.
>
> And yes, the institution _type will be the same for all accounts
> associated with a particular access token / _item.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plaid/support/issues/133#issuecomment-94111446>.
>



-- 
Joshua Bechard
--
Learn to do right! Seek justice, encourage the oppressed.
Defend the cause of the fatherless,
plead the case of the widow.
Isaiah 1:17
--
