### ISSUE TITLE
unable to retrieve pending transactions for BOFA account

### ISSUE THREAD

**Issue by ufdeveloper** [plaid/support#135]
I am using the following public API endpoint, to get the pending transactions for the user, once he is added.

https://api.plaid.com/connect/get, with options={"pending":true}

However, I am not getting any pending transactions in the results.

This is with BOFA checking account.

**Comment by ctrembl** [comment]
hey @ufdeveloper - if you could send the access token over to support@plaid.com, we'll take a closer look!

**Comment by zperret** [comment]
Follow-up via email. Closing for now...

**Comment by clintbxtreme** [comment]
I am having the same issue. I am unable to retrieve pending transactions for BofA. I have tried the public api endpoint as above and I have also tried the node library as well.

**Comment by susanfowler** [comment]
Hi @clintbxtreme!

If you send over your access token to us at support@plaid.com, we can take a closer look!

**Comment by ufdeveloper** [comment]
I am still facing the issue. Does BOfA not provide access to processing transactions? Also, Bofa mentions these transactions as processing as opposed to pending. Can you please let me know if retrieving pending/processing transactions from bofa is possible?

**Comment by susanfowler** [comment]
hi @ufdeveloper! could you send your access token to support@plaid.com?
