### ISSUE TITLE
Android dependecy on httpclient causing problems

### ISSUE THREAD

**Issue by ufdeveloper** [plaid/support#136]
I am developing an android app for plaid. Plaid has a dependency on Apache's HttpClient. However, Android uses its own version of HttpClient, which is causing a lot of problems running the application on Android. Is there a solution for this problem?

I read something about HttpClient Android port, but how exactly should this be done? Do I need to change the code in the Plaid API?

Please guide me with this.

Thanks.

**Comment by ctrembl** [comment]
Hey @ufdeveloper - thanks for reaching out. We actually strongly advise against direct mobile integrations as they would leave your API keys exposed and available to anyone. That said, we have a large number of libraries [here](https://plaid.com/docs/#libraries) that should help with getting the back-end server up and running.
