### ISSUE TITLE
Payment Required 402 Response

### ISSUE THREAD

**Issue by sam-perez** [plaid/support#137]
Hi Plaid,

A customer of ours has reported that they were unable to connect an institution, and when I looked over the logs the request to /plaid/connect returned with a 402 status and an error message of "PAYMENT REQUIRED." I looked through your status codes, but could not find a matching error message. Do you know what could be causing this particular error?

Thanks!

**Comment by zperret** [comment]
Each response should return both a standard HTTP error code and a Plaid-specific error code. The 402 error code maps to a range of Plaid error codes, many of which are user-generated failures. You can find more details on these errors [here](https://github.com/plaid/support/blob/master/errors.md).
