### ISSUE TITLE
response code 500 BOFA

### ISSUE THREAD

**Issue by mritchie712** [plaid/support#139]
What's the best way to diagnose a response code 500?  I'm able to connect to the plaid_test account just fine, but when I try to connect to my own bofa account I'm getting a response 500.  This was working fine yesterday with the same set up as today.

**Comment by michaelckelly** [comment]
@mritchie712:

Sorry that you're having issues - the response body should contain a more detailed error message in addition to the 500 status code.  Your best bet is likely to email support@plaid.com and we can look into the issue further (please include an access token if possible!).

**Comment by mritchie712** [comment]
Hello - It randomly started working again without me changing anything, so
all seems to be well for now, thanks!

**Comment by ctrembl** [comment]
@mritchie712 - thanks for the update! Glad to hear everything is working.
