### ISSUE TITLE
1702 error on bofa add attempts

### ISSUE THREAD

**Issue by HaPsantran** [plaid/support#140]
I've tried with two different bofa logins. In both cases, when I use the connect endpoint, I get:

{
    "message": "plaid error", 
    "code": 1702, 
    "resolve": "An unexpected error has occurred on our systems; we've been notified and are looking into it!"
}

I'm successfully adding accounts from other institutions so I'm not certain the issue's on my side. Is this a known issue?

Thank you!

**Comment by susanfowler** [comment]
Hi HaPsantran! 

Sorry that you're running into this problem. If you can send more information to support@plaid.com, we will take a closer look!

**Comment by BenjaminConant** [comment]
hey @susanfowler and @finoptimal-dev I am getting the same error message 

```
{ code: 1702,                                                                                                                           │Compressing objects: 100% (11/11), done.
  message: 'plaid error',                                                                                                               │Writing objects: 100% (11/11), 1.27 KiB | 0 bytes/s, done.
  resolve: 'An unexpected error has occurred on our systems; we\'ve been notified and are looking into it!',                            │Total 11 (delta 8), reused 0 (delta 0)
  access_token: 'test_chase',                                                                                                           │To git@github.com:BenjaminConant/fin-dev.git
  statusCode: 500 }
```
When attempting to step user through chase MFA for the connect API ... any guidance on how this can be resolved would be greatly appreciated!
