### ISSUE TITLE
Return owner name via the API

### ISSUE THREAD

**Issue by abrutus** [plaid/support#142]
Accountholders' name is a data point that is very important when dealing with merchants that ship products.

Eg: if bank account name is not the same as the shipping address name, then we would flag or do further verification

The equivalent in the CC world would be [AVS](http://en.wikipedia.org/wiki/Address_Verification_System)

I tested with maybe 4 different institutions and found no name. Please tag as feature request

**Comment by ctrembl** [comment]
Hey @abrutus - thanks for reaching out! If you'd like to shoot me an email directly at carl@plaid.com, I'd be happy to discuss the possibility of retrieving account holder information.
