### ISSUE TITLE
Are there future plans to make monthly bank statements available via the API?

### ISSUE THREAD

**Issue by johnnygee** [plaid/support#143]

**Comment by ctrembl** [comment]
Hey @johnnygee - currently we don't have any plans to make bank statements available via the API. That said, you can retrieve all of the data you would see on your statements (plus a lot more) by using our [Connect product](https://plaid.com/connect/).

If Connect sounds like it could meet your needs, feel free to create an account on our website [here](plaid.com/account/signup) to gain instant access to the API and a live set of API keys!
