### ISSUE TITLE
ACH via Plaid?

### ISSUE THREAD

**Issue by dudehook** [plaid/support#144]
Is there a way to initiate an ACH transfer via the Plaid API?  I was under the impression that the auth API would allow this but I don't see it.

**Comment by ctrembl** [comment]
Currently there is not. While Plaid can help you to instantly authenticate an account for ACH transfers, you'll still need to partner with a 3rd party ACH processor.

**Comment by nithinreddy** [comment]
Do you support/suggest any good 3rd party ACH processor's? I used Stripe earlier for card processing, but don't know any who does ACH processing.

**Comment by dudehook** [comment]
There are many out there. I think Stripe provides the service as well.

**Comment by nithinreddy** [comment]
Checked Stripe, but it just does card processing. Checked BalancedPayments, and they seem to be migrating with Stripe.

**Comment by amasaungvl** [comment]
You can check out forte (https://www.forte.net)  or paysimple (http://paysimple.com/)
