### ISSUE TITLE
svb transactions are all positive (even when they should represent cash inflows)

### ISSUE THREAD

**Issue by HaPsantran** [plaid/support#151]
Transactions representing Inflow to the account I'm connecting are all showing up as positive numbers.

I have not tried tartan, only the production environment.

**Comment by ctrembl** [comment]
Hi @HaPsantran - thanks for reaching out. This is a known issue that we are in the process of fixing on our end. We will update you as soon as a fix has been deployed!

**Comment by susanfowler** [comment]
This issue has been fixed! Thanks for your patience while we resolved this!
