### ISSUE TITLE
Testing Different MFA Types

### ISSUE THREAD

**Issue by ellardli** [plaid/support#152]
Hi,

Is there a way to simulate the other types of MFA similar to plaid_selections in the sandbox environment?

**Comment by ctrembl** [comment]
Yes, you will encounter the various MFA types automatically depending on the institution `type` paramter included in the initial submit call. You can find a full list of institutions and their associated requirements for MFA in our documentation [here](https://plaid.com/docs/#institutions). Let me know if you have any questions!
