### ISSUE TITLE
[Question] Test client_id and secret

### ISSUE THREAD

**Issue by dmichiels** [plaid/support#154]
Hello,

I wonder if there is an API for testing the client_id and the secret.
In our system, we allow users configure their own plaid.com account, and it will be great if we can make a test if the authentication is correct.
Is that possible without trying to create a new user?

Best regards,

Denis

**Comment by michaelckelly** [comment]
@dmichiels:

You'll want to check out our [API sandbox](https://plaid.com/docs#sandbox) - the sandbox lets you test credential validation, multi-factor authentication, and error handling!

Here's a sample request:

```console
curl -X POST https://tartan.plaid.com/auth \
-d client_id=test_id \
-d secret=test_secret \
-d type=wells \
-d username=plaid_test \
-d password=plaid_good
```
