### ISSUE TITLE
sandbox calls

### ISSUE THREAD

**Issue by arunumap** [plaid/support#156]
I am having issues connecting to sandbox.  I am trying to auth and receiving the following error:
Errno::ETIMEDOUT: Operation timed out - connect(2) for "tartan.plaid.comauth" port 443

Please advise.

**Comment by michaelckelly** [comment]
@arunumap:

Could you share the exact request, excluding any potentially sensitive information (credentials, client_id, secret, etc.), with us? Were you using a command line tool such as curl or one of our client libraries?

**Comment by arunumap** [comment]
Yes, I was using the ruby client.  Here is the call I made.

Plaid.config do |p|
      p.customer_id = 'test_id'
      p.secret = 'test_secret'
      p.environment_location = 'https://tartan.plaid.com'
    end
Plaid.add_user('auth',''plaid_selections, 'plaid_good', 'citi', {list:
true})

thanks!

**Comment by michaelckelly** [comment]
@arunumap 

I've tested that exact call with the latest version of the gem multiple times and have not seen a timeout. Is it possible your internet connection was down/going in and out when testing? We have not had any connectivity issues on either API environment (see https://status.plaid.com for more) in the past week, either.

Are you still experiencing an issue?
