### ISSUE TITLE
Can we pull personally identifiable information after connecting an institution?

### ISSUE THREAD

**Issue by pongnguy** [plaid/support#157]
Hi,

We are implementing a novel credit platform using plaid and need to verify that the account that we connect to actually belongs to our customer (could be someone else's account).  Is there any way to see the name of the person who opened the accounts or anything else like a social security number?

**Comment by ctrembl** [comment]
Hey Alfred - While Plaid does not have the ability to retrieve a user's SSN (and probably won't in the foreseeable future), we can pull in certain account holder information such as the name on file at the financial institution.

To learn more about retrieving account holder information via the API, please email me directly at carl@plaid.com.
