### ISSUE TITLE
Question: User Setup 

### ISSUE THREAD

**Issue by mrod23** [plaid/support#158]
Not sure if I missed this in the support documents. If a user's bank isn't on the institution list, what is the process to setup a user manually? By manually entering in their banking and routing information. 

If you could send an example for node.js, I'd appreciate it!

**Comment by ctrembl** [comment]
For institutions that Plaid does not currently cover, you'll need to collect account and routing numbers directly from the user and have your processing partner perform micro-deposits to verify the account ownership. This will need to be handled directly by the ACH processor, who should be able to provide additional information on how to set this up.

Don't hesitate to reach out if you have any other questions!
