### ISSUE TITLE
Python API - categories() returns 404

### ISSUE THREAD

**Issue by mritchie712** [plaid/support#160]
institutions works fine, but categories always returns 404

    institutions = json.loads(client.institutions().content)
    categories = json.loads(client.categories().content)

**Comment by Bpless** [comment]
Hi mritchie, it's working for me with version 1.0.0.  

What version are you using?

**Comment by mritchie712** [comment]
I was using 0.2.1, upgrading worked, thanks!

**Comment by Bpless** [comment]
Glad to hear it!
