### ISSUE TITLE
How may in integrate Plaid Api using PHP and CodeIgniter Framework. 

### ISSUE THREAD

**Issue by Prasenjiit** [plaid/support#161]
Hi,

I want to access from our website, which is built in CodeIgniter. 
How I will in integrate Plaid Api using PHP and CodeIgniter Framework. 
Thanks and Regards
Prasenjit

**Comment by princelonappan** [comment]
+1

**Comment by michaelckelly** [comment]
@Prasenjiit @princelonappan 

We unfortunately do not have a CodeIgniter library - while there is a [plaid-php](https://github.com/mbarany/Plaid-Backend) library, it's a bit out of date, so I would not recommend using it without committing to a bit of extra work on your end.

Your best bet is to use our API via a PHP HTTP request library. You'll be able to do everything as you would with a client library!  Do let us know if you end up building a CodeIgniter plugin - I've used it in the past and would love to see a Plaid API integration!

**Comment by oldtimeguitarguy** [comment]
I started a new PHP library for Plaid. There is still some work to do to integrate the rest of the services, but it should be able to used in any PHP application. I made Laravel-specific implementation of it as well... maybe I could make a CI-specific implementation too. If you're interested, please open up a feature request issue in the repo. I hope this helps:

https://github.com/oldtimeguitarguy/plaid
