### ISSUE TITLE
Not seeing _pendingTransaction

### ISSUE THREAD

**Issue by zsuerdieck** [plaid/support#162]
I've been using Plaid for a couple weeks, but have never seen a transaction come across with _pendingTransaction in it. I get the transactions that are pending, and I get them once they post, but nothing ties the posted to the pending. Also, I've never received a code 3 on my webhook; I get code 2 a couple times a day. Am I doing something wrong?

**Comment by susanfowler** [comment]
Hi @zsuerdieck! 

Thanks for bringing this to our attention! Would you mind sending an affected access token or two over to support@plaid.com so we can take a closer look? 

Best, 

Susan

**Comment by zsuerdieck** [comment]
Email sent.
