### ISSUE TITLE
Plaid not reporting new transactions for Chase

### ISSUE THREAD

**Issue by aquach** [plaid/support#163]
All of our Chase customers are reporting that new transactions are not appearing for them. Last week, several of them lost connectivity to Plaid (MFA reset) and we had to use PATCH to reconnect them. However, since then, these users as well as new users linking Chase have not seen any transactions appear in their account. Thanks for your help!

**Comment by eignerchris** [comment]
Also seeing this

**Comment by Anu2g** [comment]
+1

**Comment by ctrembl** [comment]
Hi all -- thanks for reaching out about this. We have already identified the underlying issue here and should have your accounts back to normal shortly. Thanks for your patience and feel free to email us directly at support@plaid.com if you have any additional questions.

**Comment by Anu2g** [comment]
Thanks @ctrembl for the fast response as always!

**Comment by dontmitch** [comment]
@ctrembl any updates on this?

**Comment by ctrembl** [comment]
Hi All -- thanks again for your patience. This issue has been resolved and your accounts should be back in a healthy state. Apologies for any inconvenience this may have caused!

As always, let me know if you have any questions.
