### ISSUE TITLE
Transaction name was incorrectly mutated

### ISSUE THREAD

**Issue by dontmitch** [plaid/support#165]
A user wrote into us saying that their rent payment was incorrectly labeled `McDonald's`. Upon further investigation, it appears that Plaid incorrectly mutated the name: the user's other rent payments for the same amount have the name `TO MCDONALD ROSS`.

Using a less aggressive classification engine would be great; when it comes to finances, I know I personally would always prefer to err on the side of correctness over cleanliness. Alternatively, accounting for amount in the classification would be nice—presumably purchases for greater than $1k aren't actually at McDonald's ;)

In the meantime, is there a way to fetch transactions with the pre-processed transaction name?

**Comment by ctrembl** [comment]
Thanks again for catching this @dontmitch! If you ever happen to notice an invalidly classified / cleansed transaction, don't hesitate to send the transaction ID with a brief description over to support@plaid.com.

While there isn't currently a way to retrieve raw transaction data through the API, we are always happy to fix/update any improperly processed transactions.

**Comment by dontmitch** [comment]
Will do! I'll compile a list of errors we've noticed and send those over to support@ later today.

**Comment by ctrembl** [comment]
Awesome, thanks @dontmitch!

**Comment by dontmitch** [comment]
☑️

**Comment by susanfowler** [comment]
thanks for sending them over @dontmitch! we're looking into them now and will get back to you soon!

**Comment by davidchambers** [comment]
> [A]ccounting for amount in the classification would be nice—presumably purchases for greater than $1k aren't actually at McDonald's ;)

Good point. Another option is for us to consult fields other than the description to decide whether to use our place matcher. In this case we could have decided not to use it because the transaction was a transfer.

**Comment by idris** [comment]
Feature Request: When we grab transactions, please send over the raw, un-cleansed transaction name as well.

**Comment by uneewk** [comment]
This may be a another manifestation of the same problem. I have seen cases where for example a transaction at a Lowes Foods grocery store was actually incorrectly classified as a transaction in a Lowes Hardware store. As a result, an incorrect location was assigned to that transaction.

**Comment by michaelckelly** [comment]
In the event of misclassified transaction data, please reach out to support@plaid.com with the affected transaction ID (the `_id` field on the API response). This information will allow us to investigate more efficiently!
