### ISSUE TITLE
US Bank Pending Transactions

### ISSUE THREAD

**Issue by brennick** [plaid/support#166]
I am using the API to get transactions using CURL and can get into my account correctly, but pending transactions are not showing up. I know they should be showing up because in my US Bank application for iOS I can see them. Plaid also is showing the correct available balance vs current balance, but not showing that one pending transaction that is making that difference.

**Comment by susanfowler** [comment]
Hi Conner!

Thanks for bringing this to our attention! Can you send the access token over to us at support@plaid.com so I can take a closer look? 

Best, 

Susan

**Comment by brennick** [comment]
Email sent, thanks.

**Comment by susanfowler** [comment]
Thanks @brennick! I'm looking into it now and will get back to you soon with more information.

**Comment by brennick** [comment]
Susan, any update on this?

**Comment by susanfowler** [comment]
Hi Conner!

We're still working on putting the fix in place. I will let you know once it has been deployed! Let me know if you have any questions in the meantime!

**Comment by brennick** [comment]
@ctrembl I see that you closed this, but I still can't seem to see any pending transactions for US Bank accounts.

**Comment by nfarina** [comment]
Also unable to see pending transactions for both US Bank accounts we've tried (also, two Chase accounts).
