### ISSUE TITLE
New category id? 10007000

### ISSUE THREAD

**Issue by SupremeA** [plaid/support#168]
My app heavily relies on category id and recently I saw a transaction with an unrecognizable id 10007000 which was a bank overdraft fee. Can you update the categories with any changes and PLEASE keep it up to date in fact I will follow that page looking for changes because as stated earlier my app GREATLY depends on those ID's

**Comment by ctrembl** [comment]
Hey @SupremeA -- thanks for reaching out about this. While the categories document here does appear to be out of date (apologies for that! - we'll update it shortly), the most reliable and always up-to-date place to stay on top of Plaid categories is to utilize our [/categories](https://plaid.com/docs/#categories) endpoint. The endpoint will also allow you to programmatically check for updates to the categories going forward.

**Comment by ctrembl** [comment]
https://github.com/plaid/support/pull/169
