### ISSUE TITLE
[Question] If an account is of type 'depository' is it safe to assume that it has a corresponding routing/account number pair?

### ISSUE THREAD

**Issue by pgorsira** [plaid/support#170]
To clarify: when I say "having a corresponding routing/account number pair", I don't necessarily mean that those numbers are available through plaid - just that they exist (even though plaid doesn't know what they are). 

Take this example: say I add a connect-only bank (no auth). Some of the accounts returned at this bank are `type: depository`. Does this mean that the account can be "ACHed from"? As in, the bank has attached a routing/account number to this account? In a sense, what I'm asking is: is the `depository` label reliable?

Hope this makes sense...lmk if my question is unclear.

**Comment by michaelckelly** [comment]
@pgorsira  

> In a sense, what I'm asking is: is the depository label reliable?

Yes - the `depository` label is accurate!
