### ISSUE TITLE
Code-based MFA for Test Environment

### ISSUE THREAD

**Issue by jamayles** [plaid/support#172]
Using the plaid-node API, After calling a list:true addAuthUser for Chase, triggering a device choice mfa step, I send a stepAuthUser('test_chase', '{"send_method": {"type": "phone"}}, callback). This sends back a 1203 (invalid MFA) error.

All of my other MFA implementations work correctly, so I know that I am otherwise reading and using the documentation correctly. I have found that you must include the type=chase while in the test environment. Is this what is causing this? Should I be including the type=chase parameter in the options object while in the test environment?

**Comment by michaelckelly** [comment]
@jamayles:

The [`send_method`](https://plaid.com/docs/#mfa-auth) is actually passed in via the options parameter:

```javascript
'use strict';

const plaid = require('plaid');

const plaidClient = new plaid.Client('test_id', 'test_secret', plaid.environments.tartan);

// Note the "null" MFA value when sending a send_method
plaidClient.stepAuthUser('test_chase', null, {
  send_method: {type: 'phone'},
}, (err, mfa, res) => {
  if (err != null) {
    console.error(err);
  } else {
    console.log(mfa || res);
  }
});
```

The response will be:

```javascript
{ type: 'device',
  mfa: { message: 'Code sent to xxx-xxx-5309' },
  access_token: 'test_chase',
  statusCode: 201 }
```
