### ISSUE TITLE
api questions

### ISSUE THREAD

**Issue by nplatias** [plaid/support#175]
I have a few questions after reading the docs and past support tickets:

 - For merchant categories, you recommend that we "verify the mappings and IDs from time to time". Are existing merchant categories subject to change, or will updates always be additions? For example, can one rely on the fact that 12012002 will always mean a fire station, or can this change?
 - I am trying to understand the lifetime of a plaid **access_token** compared to the **_id** and **_item** fields of an account, as well the **_id** field of a transaction. From what I understand an **_item** identifies a set of accounts with the same login (e.g. wells fargo debit and credit accounts linked together) and an **access_token** is generated for a **(client_id, _item)** pair to grant the **client_id** access to the accounts defined by **_item** after authorization by the owner of those accounts. My questions: 
- Under what conditions does an **access_token** become void? Fore example, when a user updates their login information, does this invalidate their **access_token** and require a new one via a PATCH to /connect?
- Are **_item** values (along with the **_id**'s of their associated accounts and **_id**'s of the transactions associated with those accounts) universal (so independent of an **access_token**'s lifetime), or are they **access_token**-specific, so they die along with the **access_token** used to retrieve them? Issue https://github.com/plaid/support/issues/60 seems to suggest the latter, i.e. that they are **access_token**-specific.
 - Does a **_user** universally identify a person who may own multiple sets of accounts each identified by an **_item**? What guarantees does plaid give with regards to the accuracy of this field (in other words, does plaid guarantee that two **_user**s are equal if and only if the respective persons they refer to are the same?)
 - What is the recommended way for staying up to date with a user's transactions now that the last_transaction parameter has been discontinued? What I am thinking is to record the date the last pull was made for each access_token (D), as well as the last transaction_id pulled from it (T). Then periodically (or on webhook notifications) request transactions whose date is at least D - n, where n is the maximum number of days it takes for a transaction to be posted. Discard received transactions with id less than T (since they should have been posted before the previous pull, hence have been received) and keep the rest. Is this approach correct? Also what value of n should be used? The docs claim that transactions are posted within at most 2 days of occurrence, does this hold for practically all transactions or should a higher value of n be used?
 - Is https the recommended protocol for the server handling webhooks? Since sensitive information is transacted (i.e. **access_token**s) it seems like http is dangerous.
 - How should one handle the possibility that the server listening to webhook requests from plaid is down? Per Issue https://github.com/plaid/support/issues/71 it seems Plaid does not retry such requests if confirmation from the listener is not received. Remedying for missed transaction additions seems easy if one keeps track of the last transaction id and date pulled. But remedying for missed transaction deletions seems much harder (is the only solution to re-pull all transactions and compare to those previously pulled?) It would be great if Plaid retried webhook requests periodically a maximum number of times until it received a 2xx from the listener (e.g. Stripe will continue trying to send the webhook once an hour for up to 3 days while it is not acknowledged).

Thank you very much for the help!

**Comment by nplatias** [comment]
Hi, do you have any updates on this? Thanks!

**Comment by nplatias** [comment]
We are stuck on some of those questions, particularly the first, fourth and sixth. It would be great if you can give some guidance. Thank you

**Comment by michaelckelly** [comment]
@nplatias - Apologies for the slow response, find answers to your questions inline:

> For merchant categories, you recommend that we "verify the mappings and IDs from time to time". Are existing merchant categories subject to change, or will updates always be additions? For example, can one rely on the fact that 12012002 will always mean a fire station, or can this change?

Exact category wording may change over time, through generally there will only be additions.

> Under what conditions does an access_token become void? Fore example, when a user updates their login information, does this invalidate their access_token and require a new one via a PATCH to /connect?

Access tokens remain valid until explicitly [deleted via an API request][1]. A successful PATCH request will not result in a new access token.

> Are _item values (along with the _id's of their associated accounts and _id's of the transactions associated with those accounts) universal (so independent of an access_token's lifetime), or are they access_token-specific, so they die along with the access_token used to retrieve them? Issue #60 seems to suggest the latter, i.e. that they are access_token-specific.

Yes, they are access token specific.

> Does a _user universally identify a person who may own multiple sets of accounts each identified by an _item? What guarantees does plaid give with regards to the accuracy of this field (in other words, does plaid guarantee that two _users are equal if and only if the respective persons they refer to are the same?)

User is actually a legacy API field.

> What is the recommended way for staying up to date with a user's transactions now that the last_transaction parameter has been discontinued? What I am thinking is to record the date the last pull was made for each access_token (D), as well as the last transaction_id pulled from it (T). Then periodically (or on webhook notifications) request transactions whose date is at least D - n, where n is the maximum number of days it takes for a transaction to be posted. Discard received transactions with id less than T (since they should have been posted before the previous pull, hence have been received) and keep the rest. Is this approach correct? Also what value of n should be used? The docs claim that transactions are posted within at most 2 days of occurrence, does this hold for practically all transactions or should a higher value of n be used?

Most connect requests generally pull 2 - 7 days worth of transaction data!

> Is https the recommended protocol for the server handling webhooks? Since sensitive information is transacted (i.e. access_tokens) it seems like http is dangerous.

Yes, we do recommend utilizing HTTPS for production webhook endpoints.

> How should one handle the possibility that the server listening to webhook requests from plaid is down? Per Issue #71 it seems Plaid does not retry such requests if confirmation from the listener is not received. Remedying for missed transaction additions seems easy if one keeps track of the last transaction id and date pulled. But remedying for missed transaction deletions seems much harder (is the only solution to re-pull all transactions and compare to those previously pulled?) It would be great if Plaid retried webhook requests periodically a maximum number of times until it received a 2xx from the listener (e.g. Stripe will continue trying to send the webhook once an hour for up to 3 days while it is not acknowledged).

I agree that webhook retries would be helpful - this is something we are actively looking into!

[1]: https://plaid.com/docs/#delete-user
