### ISSUE TITLE
plaid link native ios

### ISSUE THREAD

**Issue by nplatias** [plaid/support#176]
What's the expected release date for link's native ios support?

Thank you!

**Comment by michaelckelly** [comment]
@nplatias 

Thanks for reaching out - native iOS and Android support for Link is on our roadmap (and something we're all extremely excited about!) but we do not have a firm timeline for the launch at this time.

The best place for news about Link is our [Link GitHub repo](https://github.com/plaid/link)!

**Comment by nplatias** [comment]
Thanks a lot Michael, looking forward to it!
