### ISSUE TITLE
minimizing time from adding user to getting transactions

### ISSUE THREAD

**Issue by nplatias** [plaid/support#177]
What is the best way to minimize the time from adding a user to getting some transactions of his (say 60 days worth)? The docs recommend that the login_only = false option not be used in production, as it causes end user delays. How does the delay with this approach compare to the delay until the initial transaction pull (webhook code 0) is complete, and how many days worth of transactions does the initial transaction pull return? 

I understand that login_only = false will postpone notifying the user if their login was successful, but if we ignore that what is the fastest approach to getting back transaction data?

Thank you!

**Comment by michaelckelly** [comment]
@nplatias 

The best way to minimize the time between adding a user and retrieving transactions is to set the `login_only` parameter to `true` in conjunction with a `webhook` address in your initial request.

When the `login_only` option is `true`, you will still go through the traditional on boarding process - submitting credentials and then completing any MFA processes, if needed. At that point, no transactions will be returned, only high-level account data (names, balances, types). 

Our system will then pull an initial set of transactions for this user and, once complete, notify you via a [code 0 webhook][1], usually within 30 seconds. At that point, you can make a GET request to /connect to retrieve transactions.

You will also receive a code 1 webhook when we have completed the historical transaction pull. This will come after the code 0 webhook. You will then receive regular code 2 webhooks as we update the transactions and accounts for that user on a regular basis.

Does this answer your question?

[1]: https://plaid.com/docs/#webhook

**Comment by nplatias** [comment]
Thanks for the response Michael, this makes sense.

To make my question more specific:
 - How much time would the initial request with login_only = true take to complete for a transaction window of the last 60 days?
- How many days worth of transactions does the initial transaction pull return?

If the the answer to the first question is < 30 seconds, would this not be faster than waiting for the webhook request after the initial pull is complete? My goal is to get 60 days worth of transactions as fast as possible.

Thanks a lot

**Comment by michaelckelly** [comment]
@nplatias -

> How much time would the initial request with login_only = false take to complete for a transaction window of the last 60 days?

This varies by institution and the number of transactions per account. In general, the more data there is, the longer it takes to pull.

> How many days worth of transactions does the initial transaction pull return?

By default, 30 days, though the `start_date` option allows you to customize this behavior.
