### ISSUE TITLE
Webhook for new accounts

### ISSUE THREAD

**Issue by nplatias** [plaid/support#178]
When a user who has already been added via /connect creates a new account (under the same item), which webhook code (if any) is used to notify us? Presumably it will reflect in webhook requests with code 2 when transactions from that account are pulled. Is there a better way to be notified about this?

Thanks!

**Comment by ctrembl** [comment]
That's correct, currently new or closed accounts will be reflected in the data retrieved after a code 2 webhook. Having a webhook code specific to this situation is a good suggestion and something we'll keep in mind for future versions of the API. Thanks @nplatias !

**Comment by nplatias** [comment]
Thank you Carl, makes sense!
