### ISSUE TITLE
POST Command Quickstart

### ISSUE THREAD

**Issue by stephensonj** [plaid/support#180]
Trying to test using VBScript and the MSXML2.ServerXMLHTTP or Microsoft.XMLHTTP objects.  I have an account but am simply trying to get a response from the Sample Request.  I have tried many configurations of that request posted under "Quickstart" but cannot get a valid response, usually I get the error "Access Denied" or "code: 1100, client_id missing.

Can anyone help me with the syntax of the POST request using these microsoft objects?

**Comment by michaelckelly** [comment]
@stephensonj I am unfortunately not familiar with VBScript, but a request similar to:

```
curl -X POST https://tartan.plaid.com/auth \
-d client_id=test_id \
-d secret=test_secret \
-d type=wells \
-d username=plaid_test \
-d password=plaid_good
```

should do the trick! The error message you mentioned makes me think that you are not including a body with the request.

**Comment by stephensonj** [comment]
Curl is different than VBS.  Here is my code and related function.  It is really simple but does not work.


tsUrl="https://tartan.plaid.com/connect"
tsAuth=                "?client_id=test_id" & "&secret=test_secret"
tsRequest =        "&username=plaid_test" & "&password=plaid_good" & "&type=wells"


recdata=HTTPPost(tsUrl, tsAuth, tsRequest)
MsgBox(left(recdata,500))



Function HTTPPost(sUrl, sAuth, sRequest)
'               Set oHTTP = CreateObject("MSXML2.ServerXMLHTTP")
                Set oHTTP = CreateObject("Microsoft.XMLHTTP")
                WITH oHTTP
                                .Open "POST", sUrl, false
                                WScript.Echo "Sending request to the server... "
                                .SetRequestHeader "Content-Type", "application/x-www-form-urlencoded"
                                .SetRequestHeader "Content-Length", Len(sAuth & sRequest)
'                               .Send sAuth & sRequest
                                .Send
                End With
                HTTPPost = oHTTP.responseText
                Set oHTTP = Nothing
End Function


Jeff
