### ISSUE TITLE
Plaid Doc's Suggested Edit

### ISSUE THREAD

**Issue by gregoryz7** [plaid/support#181]
excerpt from plaid Add User Docs:
"To add a new end-user, submit their institution type, credentials, and email address to the /connect endpoint. In certain cases, depending on the Financial Institution, you..."

I think "email address" is a typo in your support documents. institution, credentials such as Username (which could be an email but not always) and Password need to be submitted.  I'm new to using github so this may be posted incorrectly.

**Comment by michaelckelly** [comment]
@gregoryz7

Thanks for the heads up! You are correct - `email` is not a required parameter when adding a new user. We'll get that updated shortly!

**Comment by gregoryz7** [comment]
Happy to help!
