### ISSUE TITLE
Is CORS supported by any environment?

### ISSUE THREAD

**Issue by sudodoki** [plaid/support#182]
Hi! 
Got a question regarding CORS support - do you plan to add corresponding headers to provide ability to query API directly from clients using ajax calls?

**Comment by ctrembl** [comment]
Hi @sudodoki -- this is not something Plaid supports as it is not a secure method of sending sensitive information such as your `client_id` and `secret`. All of your traffic should be proxied via server, where CORS is not a concern.

I would highly recommend checking out [Plaid Link](https://github.com/plaid/link) for your implementation. Link handles credential submission, error handling, and multi-factor authentication flows, all within a sleek drop-in module. Let us know if you have any other questions!
