### ISSUE TITLE
wells data availability

### ISSUE THREAD

**Issue by nplatias** [plaid/support#183]
I have found the following two issues when connecting wells accounts:
1) I have only been able to get 1 month of history for wells credit accounts, even though the spec says that 2 months of historical data should be available
2) For logins that have both credit and checking accounts under them, I have only been able to get 1 month of history overall (when I expect 18 months of history for the checking account per the spec).

Thank you!

**Comment by guimonz** [comment]
This is affecting us too guys, any updates?
We only care about the depository accounts, but history is pretty important for us.

**Comment by charleswli** [comment]
Hi @nplatias and @guimonz,

Thanks for reaching out and apologies for the issues. Could you please email support@plaid.com with the affected access tokens? We'll take a look.
