### ISSUE TITLE
interruptions in the connect process

### ISSUE THREAD

**Issue by nplatias** [plaid/support#184]
I am running into the same issue as @pgorsira in #85. In particular I don't understand why the connect process needs to restarted from scratch every time.

What state do the plaid servers maintain during the connect and connect/step process? In order to support multiple questions asked in a sequence you must be maintaining a "next unanswered question" for each access_token, which you return when the previous question is successfully answered. Why don't you make /connect/step return that when passed a specific access token but no/mistaken mfa field, in order to make interruptions easy to deal with? That way users can continue the mfa process where they left off, without having to re-submit username & password as well as all previous mfa steps.

Thanks!

**Comment by michaelckelly** [comment]
@nplatias 

Thank you for the feedback on the add user flow - I've passed it along to our API team!
