### ISSUE TITLE
error in the docs: mfa parameter not required for /connect/step

### ISSUE THREAD

**Issue by nplatias** [plaid/support#185]
This is just a note that there in an error in the docs -- the "mfa" parameter is not required for the /connect/step endpoint, as the first step in a code-based mfa flow can be a request to /connect/step with an options='{"send_method": XXX}' parameter but no "mfa" parameter (as you also demonstrate in an example).

**Comment by michaelckelly** [comment]
@nplatias - Thanks for the heads up - we'll clarify that section!

**Comment by michaelckelly** [comment]
Thanks @nplatias - way to slow on the response here, but this has been fixed internally and will be reflected in the public docs in the next few days. Thank you again for raising.
