### ISSUE TITLE
maximum transaction post delay

### ISSUE THREAD

**Issue by nplatias** [plaid/support#186]
1) What is the maximum delay between the time a transaction occurs (e.g. the physical card is swiped) and the time that transaction is available from the /connect/get endpoint? The docs say it's "from a couple minutes to a couple days", but I have observed posting delays on the order of 3-4 days. Knowing the max precisely is very important for us in order to make sure we are not missing any transactions.

2) Do the *gte* and *lte* parameters of the /connect/get endpoint filter by transaction **occurrence** date or transaction **posting** date (i.e. date the transaction is first available under /connect/get)?

Thanks!

**Comment by michaelckelly** [comment]
@nplatias The maximum post delay can vary significantly and is ultimately controlled by the bank itself. That being said, the majority of transactions post within a couple of days.

The `gte` and `lte` parameters sort transactions by the posted date.

**Comment by nplatias** [comment]
Thanks @michaelckelly!

Does this imply that asking for transactions with gte equal to the last date we pulled in UTC (and no lte) guarantees we will never miss any transactions?

**Comment by nplatias** [comment]
Do you have any updates on this? Your advice is appreciated!

**Comment by nplatias** [comment]
@michaelckelly can you please clarify the above question, it is very important for us to not miss any transactions.

The confusion comes from the distinction between transaction post date and transaction occurrence date. The docs claim that "The date in the transaction will be as close to the original transaction date as possible." However, you said that time filtering is done on transaction **posting** date, not transaction **occurrence** date. Does this mean that a request for transactions with date at least 1/1/2016 may return a transaction that occurred on 12/27/2015 (and whose date attribute will be 12/27/2015), because it was posted on or after 1/1/2016?

I would also appreciate an answer to my previous question (which is of course directly related to this).

Thank you!

**Comment by ritec** [comment]
Did you find answers to these questions? If so what were they, I am wondering the same thing.

**Comment by michaelckelly** [comment]
Plaid will return the date the transaction was considered 'posted', as determined by the financial institution.

Also - please feel free to direct questions such as this to support@plaid.com, which is monitored more often than this!
