### ISSUE TITLE
Wells Fargo unable to connect

### ISSUE THREAD

**Issue by Alok-Sharma** [plaid/support#187]
I'm having problems adding a wells fargo user, with the request simply timing out. I tried using the same account (and a few other wells fargo accounts) on demo.plaid.com, and the demo website was unable to add either. 

Is there some issue with wells fargo accounts right now?

**Comment by swinton** [comment]
+1 same issue here, unable to add a wells fargo user.

**Comment by michaelckelly** [comment]
@Alok-Sharma and @swinton 

Apologies for the issues that you both have experienced - please get in touch with support@plaid.com and we will get this resolved!

**Comment by swinton** [comment]
Thanks for the quick reply :+1:

**Comment by swinton** [comment]
Still having a problem with Wells. I hear they were experiencing issues a couple of days ago, and apparently pushed a fix to rectify, but it's still not working for me.

I've set up an example app to test with, using Link: https://plaid-link-demo.herokuapp.com/

Here's the error I get:

![](https://www.dropbox.com/s/yqw6xunynhypomr/Screen%20Shot%202015-09-03%20at%2010.36.06%20AM.png?dl=1)

**Comment by Alok-Sharma** [comment]
Wells Fargo started to work.
