### ISSUE TITLE
1702s on B of A sync

### ISSUE THREAD

**Issue by Anu2g** [plaid/support#190]
Hey there,

Around 540p today, we got a few 1702s ("code":1702,"message":"An unexpected error has occurred on Plaid's systems; Plaid has been notified and are looking into it!"), while a user of ours was trying to sync their B of A. The user is very willing to work with us, so I can likely have her recreate the error at will.

Glad to chat privately to give you token info, etc, if that helps debug it. Thanks for the great support as always.

Regards,
Anu

**Comment by steaks** [comment]
+1

**Comment by alzap** [comment]
+1

**Comment by michaelckelly** [comment]
@Anu2g @steaks @alzap 

Apologies for the radio silence here - please get in touch with us at support@plaid.com with the access token or timestamp of the request - we'll dig into it from there!
