### ISSUE TITLE
Connecting an account multiple times

### ISSUE THREAD

**Issue by t3jem** [plaid/support#193]
If a client "connects" the same user/bank multiple times (i.e. I may have a user that uses the plaid link widget to log into an account multiple times and my app doesn't prevent this), does this count as several users in regards to plaid pricing or does plaid see these multiple connects as the same user and only charge for a single user regardless of number of "connects" for the account?

I've done a little testing and it looks like the account ids change with each subsequent connect which seems to imply that each connect counts as a separate user, but i wanted to confirm before attempting to prevent multiple connects.

**Comment by colinloretz** [comment]
+1 on this question

**Comment by michaelckelly** [comment]
@t3jem @colinloretz 

> If a client "connects" the same user/bank multiple times (i.e. I may have a user that uses the plaid link widget to log into an account multiple times and my app doesn't prevent this), does this count as several users in regards to plaid pricing or does plaid see these multiple connects as the same user and only charge for a single user regardless of number of "connects" for the account?

Yes, it does count as several users in regards to pricing (as well as the 100 free users for development purposes)!
