### ISSUE TITLE
Webhook SSL

### ISSUE THREAD

**Issue by alejandrod** [plaid/support#196]
It looks like the webhook doesn't like https. I want to be sure if it's an issue with our certificate (provided by Comodo) or the webhook doesn not support https.

Thanks!

**Comment by michaelckelly** [comment]
Hi @alejandrod -

We do support HTTPS for webhooks (and certainly recommend using it) - this is likely a certificate issue. Mind dropping us a note at support@plaid.com with your client ID and the webhook URL you're attempting to use? We'll dig into a bit more from there.

**Comment by alejandrod** [comment]
sounds good

**Comment by michaelckelly** [comment]
Great! Going to go ahead and close this issue.
