### ISSUE TITLE
Error 1702 on test requests

### ISSUE THREAD

**Issue by Alok-Sharma** [plaid/support#197]
I've been receiving 1702s ('An unexpected error has occurred on our systems') while trying to connect the test user 'username- plaid_test, password- plaid_good'. This I'm attempting from Java code, by executing POST requests.
However, if I use a REST client to execute this POST request, everything works fine.

**Comment by michaelckelly** [comment]
Hi @Alok-Sharma - 

Mind sharing a sample Java code snippet that is causing the 1702 error?

**Comment by Alok-Sharma** [comment]
Hi @michaelckelly 
[Here is the code](https://github.com/Alok-Sharma/Stash/blob/master/app/src/main/java/aloksharma/ufl/edu/stash/MainActivity.java). The entire class isn't doing anything at all, except trying to call Plaid, so the entire code is right there.

**Comment by Alok-Sharma** [comment]
@michaelckelly just noticed, if I don't set the headers ('Content-type' and 'Accept'), then I receive an 1100 error (client_id is missing).

**Comment by Alok-Sharma** [comment]
@michaelckelly thanks a lot. It turns out it was an embarrassingly stupid mistake on my part.

**Comment by michaelckelly** [comment]
@Alok-Sharma 

Glad you figured it out, for future reference, send methods should be in the form:

```json
{"send_method": {"type":"email"}}
```

That being said, you also caught a bug with our API sandbox - we should have returned an `invalid send_method` error there as opposed to a 500. We'll push out a fix for that in the coming days - sorry for the troubles!

**Comment by Alok-Sharma** [comment]
@michaelckelly 
Glad I could help. Yay to unknowingly pointing out bugs!
