### ISSUE TITLE
vb.net / c# issues

### ISSUE THREAD

**Issue by chudles** [plaid/support#201]
Anyone had success calling plaid api's via vb.net or c#?

Neither of these allow you to send data along with a GET (Cannot send a content-body with this verb-type.).  But if I switch to a POST plaid seems to give a 404 error.

I'm experimenting with something simple, trying to do:
https://tartan.plaid.com/institutions/search
q=navy

I'm using code like:
oRequest = WebRequest.Create(sURL)
		
with oRequest
	.ContentType = "Content-Type: application/x-www-form-urlencoded"
	.Method = sMethod
	
	if (sData <> "") Then
		'convert from string to bytearray
		aByteArray = Encoding.UTF8.GetBytes(sData)
		.ContentLength = aByteArray.Length
		oDataStream = .GetRequestStream()    'here I get the cannot send with GET
		oDataStream.Write(aByteArray, 0, aByteArray.Length)
		oDataStream.Close()
	end if
end with

try
	oResponse = oRequest.GetResponse()
	oStreamReader = New StreamReader(oResponse.GetResponseStream())
	
Catch oException as Exception
	'here I get a 404 if calling with POST
End Try

**Comment by tmarkovski** [comment]
Since it's a GET request, it doesn't have a body, hence setting the Content-Type (of the body) serves no purpose. You should send your parameters as part of the URL, in a query. Here's a sample code using `System.Net.Http.HttpClient`:

            var client = new HttpClient();
            var q = "td";
            var response = await client.GetAsync($"https://tartan.plaid.com/institutions/search?q={q}");
