### ISSUE TITLE
Can't update webhook for test user

### ISSUE THREAD

**Issue by creotiv** [plaid/support#204]
Both /auth and /connect not working.
When sending PATCH request with data:
{'access_token': 'test_citi', 'secret': 'test_secret', 'options': {'webhook': 'http://requestb.in/12mft4t1'}, 'client_id': 'test_id'}
i get error:
HTTP_CODE: 401, Error #1109 - unauthorized product. The sandbox client_id and secret can only be used with sandbox credentials and access tokens. See https://plaid.com/docs/#sandbox.

**Comment by creotiv** [comment]
In same time as i see from GET request, webhook was set. So this is strange error

**Comment by creotiv** [comment]
Also how i can test webhooks? How i can initialize webhook call?

**Comment by fazibear** [comment]
Did you find any solution ? Try to test webhooks but don't get any requests from plaid ?

**Comment by creotiv** [comment]
@fazibear Nope, still don't know what to do with this.

**Comment by c316** [comment]
+1 here. I'm also sending an email to support to see how to fix this.

**Comment by michaelckelly** [comment]
@creotiv @fazibear @c316 

At this time, our sandbox only supports testing code 0 / initial transaction pull webhooks:

```bash
curl -X POST https://tartan.plaid.com/connect \
-d client_id=test_id \
-d secret=test_secret \
-d username=plaid_test \
-d password=plaid_good \
-d type=wells \
-d options='{"login_only":true,"webhook":"[WEBHOOK URL]"}'
```

Our "webhook docs":https://plaid.com/docs#webhook provides an overview of the other webhook types and payloads!
