### ISSUE TITLE
Long tail institutions

### ISSUE THREAD

**Issue by istx25** [plaid/support#206]
Hey! I am trying to find my bank in the long tail institutions search.

How would I find information on RBC (Royal Bank of Canada) and Tangerine (Child company of Scotiabank)? 

Any help is appreciated. :)

**Comment by uneewk** [comment]
Do a search using the API e.g. curl -G https://tartan.plaid.com/institutions/search -d q=Royal

You might want to pipe the results to a file and search that as there could potentially be many hits

**Comment by istx25** [comment]
Thanks @uneewk. I ended up figuring it out, but I appreciate you commenting. Hopefully this helps someone else who comes looking! :smile:
