### ISSUE TITLE
User listing

### ISSUE THREAD

**Issue by thomasw** [plaid/support#207]
Does Plaid provide a user list API endpoint? If they do, how does one use it with the Python client?

Without such an endpoint, it seems as though it's impossible to delete users if their IDs weren't persisted locally when those users were first created. Is that correct?

**Comment by nicksergeant** [comment]
Same question here. Seems very difficult to manage keys if they were accidentally created during development.

**Comment by michaelckelly** [comment]
@thomasw @nicksergeant 

Plaid does not provide an API endpoint to retrieve all access tokens at this time. We recommend storing all access tokens that you create in a persistent, secure datastore!

**Comment by thomasw** [comment]
What do you suggested partners do if they didn't persist tokens and created accounts using your production API? There seems to be no way of cancelling those accounts, which means paying for them indefinitely? I'm in exactly that situation and would like all upgraded accounts associated with my production account cancelled.

More generally though, you're basically saying that there's no way of doing any sort of automated subscription reconciliation. That seems absolutely fantastic for you guys, and terrible for all of your partners.

**Comment by michaelckelly** [comment]
@thomasw 

> What do you suggested partners do if they didn't persist tokens and created accounts using your production API? There seems to be no way of cancelling those accounts, which means paying for them indefinitely? I'm in exactly that situation and would like all upgraded accounts associated with my production account cancelled.

We're absolutely not interested in billing you for any access tokens that you do not want to maintain! If you do not have the tokens available, please drop us a note at support@plaid.com and we can send them via a secure messaging service.

To add some context - we view an API endpoint that would directly provide all access tokens for a given set of API keys as a security concern. We're working on ways to make this data more accessible to our customers (we do realize there are many legitimate use cases, billing & cost auditing being one of them). That being said, we won't provide this functionality until we can do so in a manner that meets our security standards.

Happy to answer any additional questions that you might have around this!
