### ISSUE TITLE
Intuit sandbox webhook issue

### ISSUE THREAD

**Issue by pgorsira** [plaid/support#211]
Quick issue - when you connect an intuit account in the sandbox you get access token `test_<intuit_institution_id>`. However, when the sandbox webhook comes in, it comes in w/ `test_intuit` access token. It should be the same as the first token.

**Comment by michaelckelly** [comment]
Thanks for raising @pgorsira - we're in the process of fixing this issue.

Please feel free to reach out to support@plaid.com in future with any other bug reports!

Related to https://github.com/plaid/support/issues/250.
