### ISSUE TITLE
Balance endpoint + longtail institutions

### ISSUE THREAD

**Issue by aatreya** [plaid/support#212]
The balance endpoint is advertised as offering real-time account balance information at the time of the API call. This appears to work well for directly-accessed institutions, but for long-tail institutions the data returned is often stale. Is this behavior expected?

**Comment by michaelckelly** [comment]
@aatreya 

The /balance endpoint returns real-time account balance information - if that is not the case for some of our longtail institutions, please get in touch with support@plaid.com so we can investigate. Please include the item ID or access token, too!

**Comment by otymartin** [comment]
@michaelckelly Hey, just a follow up to the OP's question. are realtime balances only available to the non-longtail institutions?

**Comment by michaelckelly** [comment]
@otymartin - The balance product is supported for all institutions, that is, both institutions that Plaid directly supports and longtail institutions!

**Comment by otymartin** [comment]
@michaelckelly Wicked nice - Now my only question is what is realtime balance? I have a $100 balance, I buy a 5 dollar bigmac. Im using `BalanceTracker` the app. Will it automatically update right when I swipe or is there a delay? Also `last Q: ` Can I retrieve historical balances based on date and time? eg.`balance at 11:59pm every day in March 2016`?
