### ISSUE TITLE
chase webhooks on api.plaid.com are extremely slow

### ISSUE THREAD

**Issue by nplatias** [plaid/support#213]
Code 0 sent after 14' 46'', Code 1 sent after 33' 1'', which are an order of magnitude slower than the docs suggest.

Thanks!

**Comment by idris** [comment]
This happened to me the other day also.  Plaid said they were having issues with Chase (even though the status page has no mention of it).

**Comment by nplatias** [comment]
Thanks @idris!

**Comment by michaelckelly** [comment]
@nplatias -

I'm sorry you experienced slow webhook requests from Plaid. We're constantly working to decrease the latency between Plaid's systems in the banks - we've rolled out multiple changes in the past few weeks as part of this goal.

If you're still having trouble with a particular access token, please send it to support@plaid.com and we'll be happy to investigate further.
