### ISSUE TITLE
Do transactions always arrive in order?

### ISSUE THREAD

**Issue by idris** [plaid/support#214]
When I get a webhook for new transactions, I just request all transactions with a date greater-than or equal to the last transaction I have for the account (including pending transactions).

Is this guaranteed to catch everything new?  Or how else can I know what to query for in Plaid?

The reason I'm asking is because I have a user who is missing a transaction.  I have other transactions on that day for this user, but one is missing.. that's not good.

**Comment by idris** [comment]
Got a very helpful reply from Carl @ Plaid

> yes, transactions are returned in reverse chronological order (most recent first). Due largely to the time that it takes for some pending transactions to post (such as hotel or rental car holds, etc.), our recommendation would be to set the window to 1-2 weeks back when retrieving new transactions. That way, you can be sure to catch everything new!

**Comment by aatreya** [comment]
So, is there any way to ask Plaid for all transactions that have posted since a given date, or do API users have to manually determine which transactions are new?
