### ISSUE TITLE
API webhook verify

### ISSUE THREAD

**Issue by c316** [plaid/support#216]
Is there a way to verify that a webhook was actually sent by Plaid?

**Comment by michaelckelly** [comment]
@c316 

Good question! One method of verifying the validity of a webhook is to validate that the request payload conforms to Plaid's webhook body structure. You can also confirm that the `access_token` sent in the webhook payload is one that you have in your database.

If you'd like to discuss this more, please shoot us a note at support@plaid.com.

Thanks!
