### ISSUE TITLE
Set webhook for all requests

### ISSUE THREAD

**Issue by c316** [plaid/support#217]
Is there a way to setup a webhook for all events that would either be the same URL, (domain.com/webhooks) or include something in the URL to distinguish this event immediately (domain.com/webhooks/:_id)? I know I can do this with each request, but seems like this is something that could also be in the control panel on the plaid.com site. 

Thanks

**Comment by michaelckelly** [comment]
@c316 

At this time, webhooks are set at the access token level via API requests. We realize this option can be limiting at times, though, and are looking for ways to make it easier to manage webhooks for all your users. Thank you for the feedback!
