### ISSUE TITLE
Name: "CHECK # 0xxxxx1969" doesn't display correctly 

### ISSUE THREAD

**Issue by c316** [plaid/support#218]
Inside transactions If the name field contains "CHECK # 0xxxxx1969" it is recorded as "CHECK #"

I'm using a USAA account to find this, so I don't know if this always happens, but it does with all the Check transactions in USAA. 

Is this intended, or a bug?

**Comment by c316** [comment]
Disregard, it seems that MongoDB is causing everything to the right of the "#" to disappear before it is inserted into the colleciton.

**Comment by c316** [comment]
Ok, I did some more investigating and it does seem that some of these are not coming over and other are coming through. In USAA they all have check number, but not in the response from the server. I'm logging the response even before I try to store it and there are many of these "CHECK #" where there should also be a number after the "#".

**Comment by chrisbonisa** [comment]
How or was this resolved? I'm getting the exact same behavior with a Wells Fargo business account.

**Comment by c316** [comment]
This hasn't been resolved. I haven't heard from Plaid on this yet.

**Comment by michaelckelly** [comment]
For transaction data quality questions, please reach out to support@plaid.com with the affected transaction ID so that we can investigate!

Apologies for the delayed response here - we monitor support@plaid.com regularly and will be able to respond more quickly there.
