### ISSUE TITLE
Unique access tokens

### ISSUE THREAD

**Issue by steaks** [plaid/support#219]
Hey there,

I really appreciate the ability to create test accounts via username: plaid_test.  However, I'd like it if plaid_test always returned unique access tokens.  

Right now plaid_test for bofa returns "test_bofa", plaid_test for chase returns "test_chase", etc.

I have code that mostly mitigates this issue.

```
if (!isTestAccount(accessToken) {
  //run regular code 
} else {
  //run other code
}
```

But I'd prefer to be able to rely on access tokens being unique.  Something like test_bofa{guid} or test_chase{guid}.

Thanks!

**Comment by alzap** [comment]
I agree with Steven's suggestion.  In addition, the test data should have a more recent date.

**Comment by andyburke** [comment]
I'd like to pile on:

1) I agree with different tokens being returned.

2) The returned test data should have unique routing and account numbers as well.

**Comment by michaelckelly** [comment]
Thanks for the feedback - we're working on improvements to our API sandbox to make it a more robust tool to test and build your Plaid integration. Keep an eye on our [blog][1] for news and announcements on that front.

[1]: blog.plaid.com
