### ISSUE TITLE
Bank of America MFA issue

### ISSUE THREAD

**Issue by yumikohey** [plaid/support#222]
We had couple users who were not able to verify their BoA accounts. It's difficult for us to test on our side. We tried to test with `plaid_test` for one question case and three questions case. We also tested a real account, which account's security answers are the same. All these user cases passed the MFA though.

Could you share some sample codes, which can handle BoA's case?

**Comment by michaelckelly** [comment]
@yumikohey -

The flow you outlined -- testing with the sandbox API credentials -- will work for all production Bank of America accounts (and, in general, all Plaid-supported institutions). If you're having trouble with a specific account, please share any available information (access token, time of request, etc.) with support@plaid.com.
