### ISSUE TITLE
Documentation Error for /info Response

### ISSUE THREAD

**Issue by patrickpilch** [plaid/support#223]
Relevant docs: https://plaid.com/docs/extended/#retrieve-info-data

Current documentation states the format for `.info.emails` as follows:
```json
"emails": [
      {"data":"frodo.baggins@plaid.com", "type":"primary"}],
```

But the /info endpoint returns:
```json
"emails": [{
			"primary": true,
			"type": "e-mail",
			"data": "frodo.baggins@plaid.com"
		}],
```

**Comment by michaelckelly** [comment]
@patrickpilch 

Thanks for picking up on this - we'll get this sorted out!

**Comment by patrickpilch** [comment]
I also found that in production there is an additional undocumented field named `country` coming through in the data object.
