### ISSUE TITLE
Question-based MFA does not work when we receive multiple questions in a response.

### ISSUE THREAD

**Issue by steaks** [plaid/support#225]
Many of our users are not able to sync their long-tail banks because of a Question-based MFA issue.  When we receive multiple questions in one response, we end up in an infinite loop of MFA questions.  PNC (a large bank on the east coast) is one of the banks having this issue.

_Please, feel free to email me at steven@hurdlr.com for more info :)_

Here is the scenario that is failing:

1) Connect to bank:
```
curl -X POST https://api.plaid.com/connect \
  -d client_id={HURDLR_CLIENT_ID} \
  -d secret={HURDLR_SECRET} \
  -d username={UserName} \
  -d password={PASSWORD} \
  -d type=2866
```
2) Get response with first MFA question:
```
{
  "type": "questions",
  "mfa": [
    {
      "question": "What was your high school mascot?"
    }
  ],
  "access_token": "{ACCESS_TOKEN}"
}
```
3) Answer first MFA question correctly:
```
curl -X POST https://api.plaid.com/connect/step \
   -d client_id={HURDLR_CLIENT_ID} \
   -d secret={HURDLR_SECRET} \
   -d mfa="{MASCOT}" \
   -d access_token={ACCESS_TOKEN}
```
4) Get two more MFA questions:
```
{
  "type": "questions",
  "mfa": [
    {
      "question": "What was the name of your High School?"
    },
    {
      "question": "In what city were you born? (Enter full name of city only)"
    }
  ],
  "access_token": “{ACCESS_TOKEN}”
}
```
5) Answer both MFA questions
```
curl -X POST https://api.plaid.com/connect/step \
  -d client_id={HURDLR_CLIENT_ID} \
  -d secret={HURDLR_SECRET} \
  -d mfa='["{HIGH_SCHOOL}", "{CITY}"]' \
  -d access_token={ACCESS_TOKEN}

6) Get same MFA question again

{
  "type": "questions",
  "mfa": [
    {
      "question": "In what city were you born? (Enter full name of city only)"
    }
  ],
  "access_token": "60a67d13dfe21bb74473ecc7e38807ac492685623e2d65b77b61b81f1c7f17e75376c66b00ebe1a01f83b8940bdf2b267601abbffcc19edfd1409fca40cd7fb3142efeff15b427a61d08f6fa3fdab1e6"
}
```
Step 6 continues repeatedly even when I answer with the correct response.

_Note: I've tried a bunch of iterations for step 5.  I've tried to answer question 1, then question 2.  I've tried to answer only question two.  Etc.  However, none of my attempts have worked._

_Note: Step 4 seems to be the issue.  Myguess is that this issue is related this comment: github support issue:_

> That would work fine for question-based MFA, as each question is returned one at a time for banks currently supported. (It's possible that could change when a new bank is added in the future)

Thanks!

**Comment by michaelckelly** [comment]
@steaks 

Thanks for the comprehensive steps to repro! We've identified an issue with our handling of multiple question MFA for some of our longtail institutions - we hope to have a fix deployed in the next day. I'll keep this issue updated!

Thank you for your patience - feel free to reach out to support@plaid.com with additional questions as well.

Michael
