### ISSUE TITLE
Addition limit exceeded

### ISSUE THREAD

**Issue by pspiro** [plaid/support#226]
Hi, I am working on my first Plaid program (in Java). Everything was working hunky-dory, but suddenly I getting the following error on every call:

**Exception in thread "main" 1112: addition limit exceeded  You have reached the maximum number of additions. Contact us to raise your limit.**

I am only fetching data for a single account. Can someone tell me what I need to do? Thank you.

-Pete Spiro

**Comment by michaelckelly** [comment]
@pspiro -

Please get in touch with support@plaid.com - we can help reset your addition limit from there!
