### ISSUE TITLE
Is there a way to know which type of user

### ISSUE THREAD

**Issue by c316** [plaid/support#227]
If all I have is an access token, can I determine via API call if this user is an Auth or Connect user (or both)?

Specifically I want this information for a delete operation I'm trying to run. Currently I run both the deleteAuthUser and deleteConnectUser Node functions, but one always errors (which I think is probably expected behavior).

**Comment by michaelckelly** [comment]
@c316 

This is something that you have to manage on your end at this time. A single `DELETE` request will remove the user across all Plaid products, though. That is, the access token is no longer valid once Plaid has returned a 200 response for a `DELETE` request.
