### ISSUE TITLE
No pending transactions for USAA accounts?

### ISSUE THREAD

**Issue by nicksergeant** [plaid/support#228]
Hi! Getting transactions down from a USAA account where there are several pending transactions, but I see specifically that none of them are in the transaction payload for the account from Plaid.

Any idea why those wouldn't be coming in?

**Comment by michaelckelly** [comment]
@nicksergeant 

You'll want to ensure that you're using the `pending` flag in the `options` parameter in the API request:

```
curl -X POST https://tartan.plaid.com/connect/get \
-d client_id=[CLIENT ID] \
-d secret=[SECRET] \
-d access_token=[ACCESS TOKEN] \
-d options='{"pending":true}'
```

Pending transactions are not returned by default.

**Comment by nicksergeant** [comment]
Thanks Michael, I am indeed making that request, but pending transactions are still not coming down. I've opened a support ticket, and it's being looked into. Thanks!

**Comment by michaelckelly** [comment]
@nicksergeant - Sounds good! We'll look into it over there, then. :)

**Comment by ro31337** [comment]
Same thing for Wells Fargo. Request is OK, but no pending transactions in response.

**Comment by ro31337** [comment]
Any idea why issue was closed? Is it resolved now or what? Could you give us update?

**Comment by michaelckelly** [comment]
@ro31337 - Please reach out to support@plaid.com, as that is monitored more often than this. If the request pertains to a specific access token, please include it (or another API identifier) in your request.
