### ISSUE TITLE
Plans to offer expedited account access?

### ISSUE THREAD

**Issue by nicksergeant** [plaid/support#230]
Do you have any plans to offer access to user accounts where refreshes of transactions happen much more frequently? We'd certainly be willing to pay a premium for our customer accounts to be refreshed say every 30-60 minutes. 

Is this a possibility in the future? As-close-to-real-time access to transactions is what we're looking for.

**Comment by Grummle** [comment]
+1

**Comment by aatreya** [comment]
+1

**Comment by michaelckelly** [comment]
This is not a planned feature at this time - thank you for the feedback, though. I've gone ahead and shared it with our API team!

**Comment by stevegraham** [comment]
@nicksergeant what's your use case for the update frequency? n.b I'm not a Plaid employee.

**Comment by nicksergeant** [comment]
@stevegraham was building a web app for managing your accounts (like Mint).
