### ISSUE TITLE
Docs and API seems to indicate Connect data functionality for Longtail institutions

### ISSUE THREAD

**Issue by uneewk** [plaid/support#232]
Docs and API seems to indicate Connect data functionality for Longtail institutions but I'm seeing the opposite. For example:
 curl -G https://tartan.plaid.com/institutions/4094
{
  "credentials": {
    "password": "COLTSpasswd",
    "username": "COLTSlogin"
  },
  "has_mfa": false,
  "mfa": [],
  "name": "Coastal Federal Credit Union",
  "products": [
    "balance",
    "connect"
  ],
  "type": "4094",
  "url": "https://www.coastal24.com"
}

When I turn around and do a connect like so:
curl -X POST https://tartan.plaid.com/connect [connection particulars removed] -d type=4094

I get

{
  "code": 1108,
  "message": "invalid type",
  "resolve": "This institution is not currently supported."
}

**Comment by michaelckelly** [comment]
@uneewk -

This error is likely because your client ID is not enabled for longtail access. Please get in touch with info@plaid.com to get set up!
