### ISSUE TITLE
Having trouble with Single Request Data with start_date option on /connect/get endpoint

### ISSUE THREAD

**Issue by uneewk** [plaid/support#233]
If I have understood the documentation correctly I should be able to do this:

curl -X POST https://tartan.plaid.com/connect [removed connection details] -d type=wells -d start_date=11/04/2015

When I do that I get 30 days worth of transaction data. I would expect the API will return data starting from the provided date.

**Comment by michaelckelly** [comment]
@uneewk - If you are still experiencing issues with setting a custom `start_date`, please reach out to support@plaid.com so that we can investigate.
