### ISSUE TITLE
Receiving removal webhooks for transactions that were not removed from the bank.

### ISSUE THREAD

**Issue by nicksergeant** [plaid/support#234]
I received a trans removal webhook to remove this transaction:

![http://i.nick.sg/image/2g0m3B2L3u0J/Image%202015-12-05%20at%207.02.59%20PM.png](http://i.nick.sg/image/2g0m3B2L3u0J/Image%202015-12-05%20at%207.02.59%20PM.png)

I checked the bank's website and the transaction is definitely still there:

![http://i.nick.sg/image/2n1G0f0w232C/Image%202015-12-05%20at%207.04.10%20PM.png](http://i.nick.sg/image/2n1G0f0w232C/Image%202015-12-05%20at%207.04.10%20PM.png)

**Comment by nicksergeant** [comment]
I also verified there were no duplicate transactions sent down.

**Comment by michaelckelly** [comment]
@nicksergeant - Closing this as I do not think this is relevant. If so, please reach out to support@plaid.com, which is monitored more regularly than this.

**Comment by nicksergeant** [comment]
👍
