### ISSUE TITLE
Wells Fargo not pulling new data

### ISSUE THREAD

**Issue by chrisbonisa** [plaid/support#235]
We have a wells fargo account that isn't pulling any new data since 12/01. We've been in touch with support via email, but its been several days and no response with any kind of status or resolution. We did find our wells fargo had a block on it and called them and removed the block. This may or may not be related but its still not pulling new data(balances and transactions). I've even gone as far as creating new access tokens(with the same wells user/pass), and it seems like its just using the old data still. Any help or pointers would be greatly appreciated!

**Comment by chrisbonisa** [comment]
Another thing thats probably related is it isn't pulling any historical data beyond 11/04

**Comment by michaelckelly** [comment]
@chrisbonisa -

I believe we worked through this directly via support@plaid.com. Please feel free to reopen if needed!
