### ISSUE TITLE
Registering non-test user fails

### ISSUE THREAD

**Issue by hdiwan** [plaid/support#237]
I can run your test code with my client_id and secret, but not with a different username. I'm using python and the REST API directly. I've put my code (without my auth information) at https://gist.github.com/hdiwan/9dc42129783a2823c2aa -- many thanks!

**Comment by michaelckelly** [comment]
@hdiwan -

I'm sorry that you're running intro trouble - I'd suggest opening an issue in the [plaid-python repository][1] for additional help with that code snippet. If a particular bank account login is giving you trouble, though, please send a note to support@plaid.com with any information you can provide.

[1]: https://github.com/plaid/plaid-python/issues/new
