### ISSUE TITLE
Regard to Long Search Institute

### ISSUE THREAD

**Issue by HaichenLiu** [plaid/support#238]
When we tried connect some institutes from long search, such as First Tech Federal, we got an error message saying the institute is not currently supported. However, the long search result shows First Tech Federal has connect function. 

My request is like:

curl -X POST https://api.plaid.com/auth \
  -d client_id=aaaaaaaa \
  -d secret=bbbbbbbbb \
  -d username=ccccccccc \
  -d password=ddddddddd \
  -d type=2852

**Comment by HaichenLiu** [comment]
Additionally, connect api doesn't work as well.

curl -X POST https://api.plaid.com/connect \
  -d client_id=aaaaaaa \
  -d secret=bbbbbbb \
  -d username=ccccccc \
  -d password=ddddddd \
  -d type=2852

**Comment by michaelckelly** [comment]
@HaichenLiu - You should not have any trouble with First Tech Federal with our Connect product (either using the test API keys (`test_id` and `test_secret`) or a longtail-approved production client ID). Here's a sample cURL request that you can copy-and-paste to test out:

```
curl -X POST https://tartan.plaid.com/connect \
-d client_id=test_id \
-d secret=test_secret \
-d username=plaid_test \
-d password=plaid_good \
-d type=2852
```
