### ISSUE TITLE
"This institution is not currently supported." on a legitimate connect request for a bank that shows that it supports connect

### ISSUE THREAD

**Issue by joeluxizhi** [plaid/support#239]
I'm trying to initiate a "connect" call on the "Discover Bank" which from the longtail search shows that it supports connect. The bank type=13796. But when I call connect on it, I get code:1108 back. 

The interesting thing is that all the long tail banks fails to connect while the native supported ones like chase or BOA are fine. What's going on there?

REQUEST:
```
POST /connect HTTP/1.1
Host: api.plaid.com
Content-Type: application/json
Connection: keep-alive
Proxy-Connection: keep-alive
Accept: */*
User-Agent: t CFNetwork/758.1.6 Darwin/15.2.0
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Content-Length: 144

{"client_id":"XXXXX","username":"XXXX","secret":"XXXXX","password":"XXXX","type":"13796"}
```

RESPONSE: 
```
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Date: Sun, 13 Dec 2015 01:41:58 GMT
Vary: X-HTTP-Method-Override, Accept-Encoding
Content-Length: 108
Connection: keep-alive

{
  "code": 1108,
  "message": "invalid type",
  "resolve": "This institution is not currently supported."
}
```

**Comment by michaelckelly** [comment]
@joeluxizhi -

It's possible that you are not enabled for our longtail integration, which is not enabled by default. Please get in touch with support@plaid.com to gain access!

**Comment by joeluxizhi** [comment]
@michaelckelly  welp. It's solved after week long chat with support. We spent couple days figuring out what we did wrong on our side. I think the problem here is the inconsistent response between APIs and bad error message leading to nowhere. And this is nowhere documented
