### ISSUE TITLE
Will we receive webhooks if there is no balance change or new transactions?

### ISSUE THREAD

**Issue by nicksergeant** [plaid/support#241]
I'm not seeing webhooks indicating transaction pulls for accounts that are inactive as far as balance/transactions go.

Is it safe to assume that we will receive no webhook if there are indeed no new transactions or updated balance information?

**Comment by michaelckelly** [comment]
@nicksergeant

At this time, code 2 webhooks (regular transaction updates) will only be fired if Plaid retrieved new transactions. Code 0 (initial transaction fetch) and code 1 (historical transaction fetch) will be fired regardless of the number of transactions Plaid retrieves.

**Comment by nicksergeant** [comment]
Gotcha. Thanks!
