### ISSUE TITLE
SVB unsupported suddenly?

### ISSUE THREAD

**Issue by andyburke** [plaid/support#242]
Previously Silicon Valley Bank was being reported as a supported institution at the /institutions endpoint, now it appears to not be supported any more. Is there any place where news about supported/unsupported changes is distributed?

**Comment by ctrembl** [comment]
@andyburke -- our beta integration with Silicon Valley Bank has been experiencing ongoing issues that have resulted in limited functionality over the past couple of weeks. As a result, we have decided to deprecate our integration with SVB until further notice.

In the meantime, you may still access [Connect](https://plaid.com/docs/#connect) data for SVB via our longtail integration. To learn more about this and to gain access, please drop us a note at info@plaid.com!

**Comment by adamlangsner** [comment]
Curious if there's an update on this. I used the `institutions/search` endpoint to find long tail integrations and I only found "SVB Private Bank Elite Credit Card" which I'm assuming doesn't give access to checking accounts at SVB. Are there any plans to re-introduce an integration with SVB? Thanks in advance!

**Comment by michaelckelly** [comment]
@adamlangsner - There are no immediate plans to re-introduce an integration with SVB in the immediate future.

**Comment by wantzjt** [comment]
Michael- do you have a list of banks not covers or you have rolling off that won't be coming back online in the near future, such as SVB? 

John

**Comment by michaelckelly** [comment]
@wantzjt - The [API Institutions endpoints][1] are the most up-to-date source of information for institution coverage!

[1]: https://plaid.com/docs/api/#institutions

**Comment by FabioFleitas** [comment]
(Posting this here, in hope that it's helpful to others, because this is the top Google search result for "Silicon Valley Bank Plaid" and this isn't explained anywhere else)

We were having issues connecting to the "Silicon Valley Bank SVB SVBeConnect" through Plaid Link. The username/password auth login weren't working. We got in touch with Plaid support and they said:
```
