### ISSUE TITLE
How can I request a new bank to be added?

### ISSUE THREAD

**Issue by steaks** [plaid/support#243]
I'd like to request OE Federal Credit Union to be added (https://oefcu.org/), but I didn't see a place to request new banks.

**Comment by ctrembl** [comment]
OE Federal Credit Union is actually already supported as one of our longtail institutions [here](https://plaid.com/docs/#long-tail-institutions) (type: 1055). In order to have your account enabled for longtail institutions, please send us a note at signups@plaid.com!

**Comment by steaks** [comment]
Oh great thanks!

My search terms must have been missing it:

```
curl -G https://tartan.plaid.com/institutions/search -d q="OE+Federal+Credit+Union"
curl -G https://tartan.plaid.com/institutions/search -d q="OE+Federal"
```

**Comment by michaelckelly** [comment]
@steaks - 

The formal name for OE  Federal Credit Union is "Operating Engineers FCU", searching for:

```
curl -G https://tartan.plaid.com/institutions/search -d q="Operating%20Engineers"
```

will yield the expected results. After looking at OE's site, it seems like OE is a common way to refer to the credit union, though - we'll work towards incorporating that into the search data going forward!

**Comment by steaks** [comment]
@michaelckelly thanks! Do you have a rough estimate about when you'd integrate that search feature?  

Note: I'm asking because it's helpful for context when working with users, not requesting it to be a high priority.
