### ISSUE TITLE
Chase account is not returning transactions

### ISSUE THREAD

**Issue by rehcgt** [plaid/support#244]
Hi there, when using https://tartan.plaid.com/connect/get with a Chase account the transactions array is always returned empty... This seems to be similar to what was reported here: https://github.com/plaid/support/issues/163

Can you assist?
Thanks.

**Comment by michaelckelly** [comment]
@rehcgt - Apologies for the delayed response. In future, please feel free to direct questions such as this to support@plaid.com, which is monitored more often than this! In your email, please include an access_token or some other API identifier so that we can more efficiently help you.
