### ISSUE TITLE
Bank of America Extra Security at Sign-in

### ISSUE THREAD

**Issue by zihehuang** [plaid/support#246]
I tried to use Plaid to sign into my Bank of America account, which has Extra Security enabled. I posted to https://tartan.plaid.com/connect and https://tartan.plaid.com/auth with all the necessary fields. However, the response I got was: 

    {
    "code": 1211,
    "message": "bofa account not supported",
    "resolve": "The security rules for this account restrict access. Disable 'Extra Security at Sign-In' in your Bank of America settings."
    }

I thought Plaid could handle code-based mfa, which is what Extra Security at sign-in is. Is this a Bank of America problem or is this working as intended?

**Comment by zachlatta** [comment]
Running into this same issue. Curious as to whether Plaid supports MFA for BofA.

The other strange thing is that I don't have extra security enabled on my account, but Plaid doesn't want to sign-in regardless.

**Comment by michaelckelly** [comment]
@zihehuang @zachlatta - Plaid does not support Bank of America accounts that have additional security settings enabled. Plaid will return the code 1211 / bofa account not supported error as included for these accounts.

**Comment by zachlatta** [comment]
I don't have extra security turned on though...

**Comment by michaelckelly** [comment]
@zachlatta - Please reach out to support@plaid.com with a timestamp of the failed request, then! Thank you!
