### ISSUE TITLE
plaid_test Incorrect webhook access tokens

### ISSUE THREAD

**Issue by steaks** [plaid/support#250]
Hey guys,

It seems something's going awry with plaid_test webhooks.  I'm not sure if this affects real accounts.

Notice the webhook access token is "test_intuit".

**/connect:**

*request:*
```
curl -X POST https://tartan.plaid.com/connect \
  -d client_id=[REDACTED] \
  -d secret=[REDACTED] \
  -d username=plaid_test \
  -d password=plaid_good \
  -d type=25628 \
  -d options='{"webhook":"http://dev.hurdlr.com/PlaidWebhookServlet", "login_only":true }'
```
*response:*
```
{
  "accounts": [ /*accounts*/ ],
  "access_token": "test_25628"
}
```

**webhook:**

```
{"access_token":"test_intuit","code":0,"total_transactions":16,"message":"Initial transaction pull finished"}
```

Thanks for looking into this!

**Comment by michaelckelly** [comment]
Thanks for raising this @steaks and apologies for the delay - this will be fixed in the coming days.

Also - please feel free to direct issues such as this to support@plaid.com, which is monitored more often than this!

**Comment by steaks** [comment]
Thanks!

I think you meant to link here: https://blog.plaid.com/
