### ISSUE TITLE
Stripe Access via Connect

### ISSUE THREAD

**Issue by matthewarkin** [plaid/support#252]
I know you can get a verified Stripe bank account token via the Link API, however it would be pretty useful if you could do this via the Auth API. 

The auth api includes the access token that the exchange_token API would give you, but it would be nice if you could just add a like `include_stripe_token` flag to include a batoken or something.

Alternatively, I did find it pretty easy to just call the API link calls but using nondocumented APIs is pretty gross.

**Comment by michaelckelly** [comment]
@matthewarkin - At this time, you must use Plaid Link in order to take advantage of the [Plaid Link + Stripe ACH partnership][1].

Also - please feel free to direct questions such as this to support@plaid.com, which is monitored more often than this!

[1]: https://blog.plaid.com/plaid-and-stripe/
