### ISSUE TITLE
Do you have a PHP laravel library?

### ISSUE THREAD

**Issue by husonghua** [plaid/support#253]

**Comment by travoltron** [comment]
I've made one, I'll package it up as soon as I can.

**Comment by husonghua** [comment]
Excellent. Look forward to it.

**Comment by Dzale** [comment]
Hi travoltron,

any progress on library ?

Best regards,
Nikola

**Comment by travoltron** [comment]
I'm pleased to announce a packaged Laravel Plaid library. [Travoltron Plaid](https://packagist.org/packages/travoltron/plaid)

I put it together kinda quickly, so there might be a bug here or there. Feel free to open an issue, and I'll take care of it as quickly as possible. Thanks!

**Comment by husonghua** [comment]
Thanks. Will check it out.

On Tuesday, June 7, 2016, travoltron <notifications@github.com> wrote:

> I'm pleased to announce a packaged Laravel Plaid library. Travoltron Plaid
> <https://packagist.org/packages/travoltron/plaid>
>
> I put it together kinda quickly, so there might be a bug here or there.
> Feel free to open an issue, and I'll take care of it as quickly as
> possible. Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/plaid/support/issues/253#issuecomment-224300114>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAzjXHcY_ha4pznd2droChMpGOfoFIvFks5qJYGSgaJpZM4HKGGZ>
> .
>


-- 
Songhua
917-294-3835
- sent from iPad and please tolerate typos

**Comment by oldtimeguitarguy** [comment]
I have also started work on a robust implementation of the Plaid API client for PHP, including some Laravel-specific features. It is not yet complete, but it adheres closely to Plaid's official documentation.

https://github.com/oldtimeguitarguy/plaid

**Comment by michaelckelly** [comment]
We do our best to keep track of officially-supported and community-driven libraries at https://plaid.com/docs/resources/.

If you'd like us to list a library you've authored, please reach out to support@plaid.com - we really appreciate community contributions!
