### ISSUE TITLE
Some names returned with suffixes are full of white-space

### ISSUE THREAD

**Issue by patrickpilch** [plaid/support#256]
We noticed some customer names with suffixes from the `info` endpoint came back with characters like `\t` `\r` and `\n` in a format like so:

```
BOB T SHMOE
		         	 			
									JR
```
After investigating a few instances, I determined that they were all from a particular institution. I understand that you are basically just forwarding the data along, but I just wanted to make you aware and perhaps consider a sanitization solution for your API consumers.

**Comment by michaelckelly** [comment]
@patrickpilch - If this is still an issue, please reach out to support@plaid.com with the access_token, item ID, or account ID so that we can investigate.

Also - please feel free to direct questions such as this to support@plaid.com, which is monitored more often than this!
