### ISSUE TITLE
Document the purpose of _user

### ISSUE THREAD

**Issue by IsaiahJTurner** [plaid/support#260]
It is returned in the response. What is it? Is there only one _user per access_token? Is _user unique to a bank regardless of the access_token?

**Comment by IsaiahJTurner** [comment]
Also, completely unrelated but the quotes are different colors on some sample responses in the documentation.

<img width="90" alt="screen shot 2016-02-19 at 2 19 27 pm" src="https://cloud.githubusercontent.com/assets/3732588/13186336/cd2ff888-d713-11e5-8553-173899970d0c.png">
<img width="87" alt="screen shot 2016-02-19 at 2 19 19 pm" src="https://cloud.githubusercontent.com/assets/3732588/13186337/cd35b7dc-d713-11e5-847b-8a349af30313.png">

**Comment by michaelckelly** [comment]
@IsaiahJTurner - The `_user` field is deprecated and can be safely ignored. It is not used.

Also - please feel free to direct questions such as this to support@plaid.com, which is monitored more often than this!
