### ISSUE TITLE
Is it possible for transaction data to change?

### ISSUE THREAD

**Issue by IsaiahJTurner** [plaid/support#263]
Will an individual Transaction always have the same response data given the same _id? I only just realized that with pending transactions, the Transaction `_id` will change. That's not clear at all in the docs.

Regardless, should I perform an update on the Transaction's I've already cloned to my database or is it safe to assume the data is identical?

**Comment by matthewarkin** [comment]
Transactions are immutable (though they can get deleted). https://github.com/plaid/support/issues/71#issuecomment-55310340 has some good details :)

**Comment by IsaiahJTurner** [comment]
Are pending transactions also immutable? if not and they are updated, will their _id remain the same?

I know pending Transactions can change when they settle and a new Transaction is created. I'm only asking about when they are unsettled. Your comment and #71 seem to imply they will not change but the docs suggest they may change.

I had read #71 before but that part had been written before pending was fully implemented. 

Thanks so much for your help!

**Comment by michaelckelly** [comment]
While very rare, transaction data can change - in general, Plaid attempts to report the data as the financial institution does. There are cases where some transaction data may be mutated due to bank operations.
