### ISSUE TITLE
Is there any way to add an info user without reauthentication?

### ISSUE THREAD

**Issue by mdaleiden** [plaid/support#264]
We are working on a solution where we want to leverage the /info endpoint to get the actual names (people, company, etc.) that are associated with an account for which the user has already authenticated using Link (so we already have the access_token for that user for authenticating other requests, such as /connect). We also have code in place to upgrade access to the "info" product and that is working without issue. However, the /info API specifically states that the user needs to be added as an "Info User" to the /info service (to generate a separate access_token for /info)using the user's online banking credentials, which we do not have, since Link captured them and only provides us with the auth access_token.

Is there any way to generate the /info user access_token without forcing the user through the entire login process again?

**Comment by michaelckelly** [comment]
@mdaleiden -

I'm sorry if the docs are not clear around this - you can indeed use the [/upgrade API endpoint][1] to access both Auth and Info without having to have the user reauthenticate. For example, assuming you are using Plaid Link with Auth, you'd make the following request to also access Info for that user:

```
curl -X POST https://tartan.plaid.com/upgrade \
-d client_id=[CLIENT ID] \
-d secret=[SECRET] \
-d access_token=[ACCESS TOKEN] \
-d upgrade_to=info
```

That request will return Info for the user. You'll also be able to make Info GET API requests!

[1]: https://plaid.com/docs#upgrade-user
