### ISSUE TITLE
MFA Code Based with Sandbox accounts

### ISSUE THREAD

**Issue by natemann** [plaid/support#265]
Are we able to test Code based MFA with the sandbox accounts. I am submitting a /step .POST with the following

{"client_id":"client_ID",
 "secret":"secret",
"access_token":"test_chase",
"options":{"send_method":{"mask":"email"}}}

but I keep getting the following error:

"code": 1204,
  "message": "invalid send_method",
  "resolve": "The MFA send_method provided was invalid. Consult the documentation for the proper format."

**Comment by michaelckelly** [comment]
@natemann 

The `mask` parameter for the `send_method` is the masked contact address. Try replacing `mask` with `type` in your example.

Specify `type` -
```
curl -X POST https://tartan.plaid.com/connect/step \
-d client_id=test_id \
-d secret=test_secret \
-d access_token=test_chase \
-d options='{"send_method":{"type":"email"}}'

Specify `mask` -

```
curl -X POST https://tartan.plaid.com/connect/step \
-d client_id=test_id \
-d secret=test_secret \
-d access_token=test_chase \
-d options='{"send_method":{"mask":"t..t@plaid.com"}}'
```

Also - please feel free to direct questions such as this to support@plaid.com, which is monitored more often than this!
