### ISSUE TITLE
add guidance to connect docs on daily frequency of data refresh

### ISSUE THREAD

**Issue by gpolyn** [plaid/support#268]
I notice that some pending transactions in a personal account do not show up in the response from connect/get, while other pending transactions do.

Did I miss some statement on how often user transaction data is refreshed  by /connect?

If there is no standing guidance, I propose adding discussion of refresh frequency to connect docs. One benefit of dependable updates is users could 'timestamp' transactions at refresh intervals, intraday.

**Comment by michaelckelly** [comment]
@gpolyn  - Plaid updates accounts 4 - 6 times per day. Please see https://plaid.com/docs/api/#user-flow for the most up-to-date information.

Also - please feel free to direct questions such as this to support@plaid.com, which is monitored more often than this!
