### ISSUE TITLE
In Plaid, is it possible to get a webhook notification when credentials expire or become invalid?

### ISSUE THREAD

**Issue by hemangmehta** [plaid/support#273]

**Comment by michaelckelly** [comment]
@hemangmehta  - This is possible, simply associate a `webhook` URL with an access token. Plaid will send a webhook whenever a error that requires user action is encountered, such as 'invalid credentials' or 'account locked'.

See plaid.com/docs/api#webhook for additional details and examples.

Also - please feel free to direct questions such as this to support@plaid.com, which is monitored more often than this!
