### ISSUE TITLE
Capital One 360 Support?

### ISSUE THREAD

**Issue by areagle** [plaid/support#278]
Is /connect support for capone360 on plaid's timeline anytime soon? I was hoping I'd be able to pull a list of recent transactions from my capital one credit card account. Cheers,

Adam

**Comment by paulholcomb** [comment]
Did you ever get a response for this?  We need this as well.

**Comment by areagle** [comment]
Nope, no response.

**Comment by jacobnbrum** [comment]
Aren't you able to do this via Longtail?
![image](https://cloud.githubusercontent.com/assets/9966112/17632958/192aec8e-6099-11e6-922f-6b975cd251fe.png)

https://plaid.com/docs/api/#long-tail-institutions-overview

**Comment by michaelckelly** [comment]
@jacobnbrum @areagle @paulholcomb -

We do not have an immediate timeline for introducing Connect support for Capital One 360. That said, we're always working to improve our product and institution coverage over time.

Also - please feel free to direct questions such as this to support@plaid.com, which is monitored more often than this!
