### ISSUE TITLE
How to get only those transaction of the selected Account

### ISSUE THREAD

**Issue by AkhileshDahat** [plaid/support#281]
curl -X POST https://tartan.plaid.com/connect/get \
  -d client_id={CLIENT_ID} \
  -d secret={SECRET} \
  -d access_token={ACCESS_TOKEN}

Response is
http code 200
{
  "accounts": [
    {object 1},
    {object 2}
  ],
  "transactions": [
    {object 1},
    {object 2}
  ]
}

I have certain requirement like I need only Account {Object 1}  transaction.Currently it pulls all the accounts transactions.
I need endpoint to get the particular account transactions.Is there any endpoint provided by plaid.

[plaidaccounttransaction](https://cloud.githubusercontent.com/assets/2920987/16658398/de4f8312-4483-11e6-967a-bcea3c937bb3.png)

**Comment by michaelckelly** [comment]
@AkhileshDahat - You can retrieve transactions for a particular account by specifying the `account` option. For example:

```
curl -X POST https://tartan.plaid.com/connect/get \
-d client_id=test_id \
-d secret=test_secret \
-d access_token=test_wells \
-d options='{"account":"nban4wnPKEtnmEpaKzbYFYQvA7D7pnCaeDBMy"}'
```

Also - please feel free to direct questions such as this to support@plaid.com, which is monitored more often than this!
