### ISSUE TITLE
addAuthUser not working for American Express on Node.js

### ISSUE THREAD

**Issue by nicholasalanbrown** [plaid/support#282]
I'm following the instructions to authorize a user on an American Express account but I get this response:

```
I20160714-16:25:44.128(-4)? { code: 1601,
I20160714-16:25:44.129(-4)?   message: 'product not available',
I20160714-16:25:44.129(-4)?   resolve: 'This product is not yet available for this institution.',
I20160714-16:25:44.129(-4)?   statusCode: 404 }
```

The documentation says American Express is supported - what gives?

Here's my code:

```
import plaid from 'plaid';
const plaidClient = new plaid.Client(myPlaidClientId, myPlaidSecrett, plaid.environments.tartan);

plaidClient.addAuthUser('amex', {username: 'myUsername', password: 'myPassword'}, function (error, response) {
  if (error) {
    console.log(error);
  }
  else {
    console.log(response);
  }
);
```

**Comment by michaelckelly** [comment]
@nicholasalanbrown - Auth is not a supported product for American Express. See https://plaid.com/docs/api/#institutions for additional information.

Also - please feel free to direct questions such as this to support@plaid.com, which is monitored more often than this!
