### ISSUE TITLE
updating existing accounts.

### ISSUE THREAD

**Issue by balakarthik2011** [plaid/support#283]
I read the documentation of updating the user's existing accounts in this [link](https://plaid.com/docs/quickstart/#updating-existing-accounts), where i have some problem,

when i try to assign the access token of a test user namely **test_chase** in the the **token** field, i am getting a error

`Error retrieving institution for public token. Make sure that the entered token is correct. If error persists, contact support@plaid.com.`

and can i know what does "test,chase,connected" indicates in the token field and what should i do update a user with his access token.

**Comment by boxymoron** [comment]
I was having similar issues with test credentials. Try using some real credentials (you can use them in tartan env). 

Once you are using real credentials:

To UPDATE a user's bank credentials you need to use the **public_token** for that user (not the access_token). The access_token is used **after** initial account set-up to pull bank info from Plaid servers.

See [Updating Existing Accounts](https://plaid.com/docs/quickstart/#updating-existing-accounts)

To get the public_token:
The public_token is POSTed to your server the first time the user authenticates (through the onSuccess() JS handler on your page (if using custom JS integration), or through the html form (if using simple integration). In practical terms this means your server-side logic has to store the public_token for that user for future credential updates.

See [JS Integration](https://plaid.com/docs/quickstart/#step-4-test-with-sandbox-credentials), specifically the JS comments in the source code.

**Comment by michaelckelly** [comment]
@balakarthik2011 

@boxymoron is correct - you'll need to initialize Link with the `public_token` for the user. For example:

```
<!-- A hidden input named public_token will be appended to this form
once the user has completed the Link flow. Link will then submit the
form, sending the new public_token to your server. -->
<form id="some-id" method="POST" action="/authenticate"></form>

<script
  src="https://cdn.plaid.com/link/stable/link-initialize.js"
  data-client-name="Client Name"
  data-form-id="some-id"
  data-key="test_key"
  data-product="auth"
  data-env="tartan"
  data-token="test,chase,connected">
</script>
```
