### ISSUE TITLE
Can the data availability be updated to include all banks + longtail?

### ISSUE THREAD

**Issue by dam13n** [plaid/support#289]
https://github.com/plaid/support/blob/master/data-availability.md

**Comment by michaelckelly** [comment]
@dam13n - Longtail data availability is provided in that document already!

**Comment by dam13n** [comment]
@michaelckelly Hmmm, but there is no Capital One, Schwab, etc...

Also, BBT not there (not a longtail).

**Comment by dam13n** [comment]
Ohhh, I see the "longtail". My bad, haha.

**Comment by michaelckelly** [comment]
@dam13n - BBT will be added in the coming days!
