### ISSUE TITLE
Is it possible to get real-time transaction updates from the webhook?

### ISSUE THREAD

**Issue by zkhalapyan** [plaid/support#291]
For example, if I use my debit card to to make a purchase, and given that this debit card has been successfully connected to plaid, can the webhook be invoked as soon as the transaction is added?

**Comment by michaelckelly** [comment]
@zkhalapyan  - Real time transaction notifications are not possible due to limitations with the financial institution's infrastructure. Plaid's system updates accounts 4 to 6 times per day, though!
