### ISSUE TITLE
Guaranteeing specific MFA responses

### ISSUE THREAD

**Issue by RyanRolin** [plaid/support#297]
Is there a way to guarantee that a specific MFA response will come back every time? For E2E testing purposes, I would like to have a set username (e.g., plaid_code) that would always result in an MFA security code response. This way, the test can safely assume that an MFA challenge will always happen.

**Comment by michaelckelly** [comment]
@RyanRolin -

Our [API sandbox](https://plaid.com/docs/api/#sandbpx) allows you to do just that. For example:

```
curl -X POST https://tartan.plaid.com/auth \
-d client_id=test_id \
-d secret=test_secret \
-d type=chase \
-d username=plaid_test \
-d password=plaid_good \
-d options='{"list":true}'
```

**Comment by Anu2g** [comment]
The sandbox only mentions how to get by with no mfa (i.e. plaid_good), and how to get a "selection-based" mfa (i.e. plaid_selections). Is there a way to get code-based or questions-based?

**Comment by Anu2g** [comment]
I see that we can force it based on the type of institution. So we're good to go. Thanks @michaelckelly
