### ISSUE TITLE
Unable to onboard Capital One account

### ISSUE THREAD

**Issue by andresn** [plaid/support#302]
Onboarding the Plaid test account works, but not with a real one. The server times out (500) without returning the MFA code prompt and I've tested via code and Postman.

**Comment by andresn** [comment]
Fwiw: we have noticed that the onboarding does work locally (as opposed to prod, or postman), the main difference is we're not using SSL/certs there.

**Comment by michaelckelly** [comment]
@andresn  - Can you please [open a support ticket][1] so that we can help you resolve this issue? Including the [API request ID][2] will also help us get to the bottom of this faster.

[1]: https://dashboard.plaid.com/support/new
[2]: https://support.plaid.com/customer/portal/articles/2670782
