### ISSUE TITLE
Allow CORS for public /institutions API

### ISSUE THREAD

**Issue by dmoss18** [plaid/support#304]
Can you allow a CORS request for the /institutions/all/search API? It's a public api (doesn't require a client id/secret) so there's no real risk. It would be easier than going to my server to have it make the  request.

**Comment by michaelckelly** [comment]
@dmoss18 - CORS is supported for that endpoint:

``
~ $ curl -v -X GET "https://api.plaid.com/institutions/all/search?q=redwood"
*   Trying 34.194.130.244...
* Connected to api.plaid.com (34.194.130.244) port 443 (#0)
...
> Accept: */*
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
< Access-Control-Allow-Origin: *
...
< 
```

Are you having trouble making the request from a browser?
