### ISSUE TITLE
Make raw transaction names available

### ISSUE THREAD

**Issue by joshcutler** [plaid/support#81]
Is it possible to also make the raw transaction names available?

By this I mean whatever is listed by the bank itself.  I have notice a number of cases where transactions are being renamed and are just incorrect.

I would much rather have access to the raw data then the augmented data w/ 5% of them wrong.

I can provide specific transaction ids if that would help debug.

**Comment by michaelckelly** [comment]
Hi Josh -- sorry for not getting to this previously.  Please do feel free to share any transaction ids that might have been parsed incorrectly with us either here or via support@plaid.com.  Thanks!
