### ISSUE TITLE
Transaction Date is posted date

### ISSUE THREAD

**Issue by aarondeutsch** [plaid/support#86]
Hey,

I am looking at some Chase transactions where the date from Plaid is the posted date instead of the transaction date.  The transactions had the correct transaction date while they were pending.  However, once the transactions were posted (today) the Plaid date became the posting date.  I can message you further details if it would help.

Thanks,

Aaron

**Comment by ctrembl** [comment]
Hey @aarondeutsch - are you guys still encountering issues with the dates associated with Chase transactions? Feel free to shoot us an email to support@plaid.com and we'll take a closer look.

Apologies for the delayed response!
