### ISSUE TITLE
No updates in certain accounts

### ISSUE THREAD

**Issue by aarondeutsch** [plaid/support#91]
Hi,

We are seeing that no transactions have been updated in Chase accounts since 1/6/2015.  Is there an outstanding issue?

Thanks,

Aaron

**Comment by ctrembl** [comment]
Hey @aarondeutsch - do you mind sending over the affected access tokens to support@plaid.com? Thanks!

**Comment by aarondeutsch** [comment]
Hi Carl,

It now appears everything is working properly with the Chase accounts.  The only remaining issue is that a previously working BofA account gets error 1212, "No valid accounts exist for this user.".  If that's weird to you I can send you the token, otherwise I'll assume everything is working properly for now.

Thanks!

**Comment by ctrembl** [comment]
@aarondeutsch - thanks for the update! Don't hesitate to reach out if you have any other questions.
