### ISSUE TITLE
Connect receiving error 1702

### ISSUE THREAD

**Issue by fwhenin** [plaid/support#92]
FIXED

**Comment by fwhenin** [comment]
NEVER MIND...After I pasted that, I realized I didn't close quote aro

**Comment by michaelckelly** [comment]
Hi there -- glad you fixed the error.  It looks like you included your client secret in this issue, though!  I have invalidated that secret on both our production and development environments.  Please email support@plaid.com to get a new secret securely.  

Thanks,
Michael
