### ISSUE TITLE
PNC log in not working

### ISSUE THREAD

**Issue by natemann** [plaid/support#93]
I am trying to log into PNC with real credentials, but I get this response every time:

message: product not available, code: 1601, resolve: This product is not yet available for this institution

**Comment by michaelckelly** [comment]
Hi Nate,

What product are you trying to access?  The [PNC extractor](https://api.plaid.com/institutions/54acb2eb9d5b8617e0d5aa86) only supports the auth and balance products currently.

**Comment by natemann** [comment]
I have a personal checking account. Trying to get transactions 

Nate Mann

**Comment by ctrembl** [comment]
Hey Nate - Transactions ([Connect](plaid.com/connect)) are not currently available for PNC accounts at this time, only account ([Auth](plaid.com/auth)) and [balance](https://plaid.com/docs/#balance) information.

**Comment by robmpreston** [comment]
I am still having this problem with Connect, despite the fact that the PNC extractor says it supports Connect. Anyone have any ideas why that would be the case?
