### ISSUE TITLE
Info for institutions

### ISSUE THREAD

**Issue by brianmgray** [plaid/support#94]
Hi plaid,
I work for a major financial institution that is in the early stages of building an Open API. We are looking for standards and possibly partners to help guide the creation of our API. Do you have documentation of how this works on the institution side? What we would need to support?

Thanks!
-Brian

**Comment by yossishm** [comment]
Same here :) Any non-screen-scrapping integration with an existing API?
If so, any reference architecture in place?

thanks,
Yossi

**Comment by ctrembl** [comment]
Hey @brianmgray, @yossishm - thanks for reaching out!

Feel free to drop me a line at carl@plaid.com and we'll get a call setup to discuss things in more depth.
