### ISSUE TITLE
Testing auth/step getting Invalid Institution

### ISSUE THREAD

**Issue by tannner** [plaid/support#97]
I'm trying to test out your Auth API, and whenever I submit a POST request to /auth/step with the following (also happening with actual client_id and secret) :

    {
        "access_token":"test",
        "mfa":"again",
        "client_id":"test_id",
        "secret":"test_secret"
    }

I get a 401 response with:

    {
        code: 1108
        message: "invalid type"
        resolve: "This institution is not currently supported."
        access_token: "test"
    }

I'd like to be able to test the step functionality and I imagine this isn't a response I would normally receive.

**Comment by tannner** [comment]
I should probably read the documentation better. Just found this:

Other Parameters: Institution type is required for ALL sandbox requests in order to better replicate institution specific steps and responses. Every access_token returned and required should be test.

Apologies for the false alarm.

**Comment by tannner** [comment]
It should be noted though that this makes testing integrated applications difficult, since now I need to drastically modify the code (including your supplied libraries, i.e. the node library) to support passing the type to all requests if I'm testing.  Is there any way around this?

**Comment by michaelckelly** [comment]
Hi Tanner-

Sorry about the hassle with that -- you're right that that is not a great flow to test with.  We're working on making it easier to use the sandbox directly & via our client libraries.

Michael
