### ISSUE TITLE
Wells not returning transactions

### ISSUE THREAD

**Issue by pgorsira** [plaid/support#98]
My request:

    curl -X POST https://tartan.plaid.com/connect \
      -d client_id={MY_CLIENT_ID} \
      -d secret={MY_CLIENT_SECRET} \
      -d username={my_wells_username} \
      -d password={my_wells_password} \
      -d type=wells

Response:

    {
      "accounts": [
       {my accounts}
      ],
      "transactions": [],
      "access_token": "{an_access_token}"
    }

Added my account about 3-4 days ago and no transactions ever appeared. Tried again just now by deleting this access token and re-adding the account.  Same response (still don't appear to be receiving any transactions).

Any ideas? Was not asked for MFA, btw.

**Comment by pgorsira** [comment]
Yo, any updates on this? Is it just my Wells account?

**Comment by susanfowler** [comment]
Hi!

Apologies for the delayed response. If you could send your access token to support@plaid.com, we'd be more than happy to look into it for you! 

Best, 

Susan 

P.S. Please do not post your access token here.
