### ISSUE TITLE
This Institution is not currently supported Issue

### ISSUE THREAD

**Issue by parchambeau** [plaid/support#99]
Hey all,

I am currently having a problem when attempting to force MFA with the username / password combo "plaid_selections" / "plaid_good".

I am able to get the MFA to be returned, but upon answering the question (ex: Chase Security Check code, answer: 1234) I get back the error "This institution is not currently supported".

This is happening with the following banks that I am trying: 

Bank of America
Chase
Citibank
US Bank

Looking up what that errors means in your documentation it seems like an "invalid type" problem. Were the types recently changed and new values for these banks need to be passed? Below are the following values I am passing for type respective to each bank.

bofa
chase
citi
us

Any help would be greatly appreciated.

**Comment by michaelckelly** [comment]
Hi Patrick--

Sorry that you're having trouble.  If you could share the exact request you made (without your client id and secret), that would be helpful.

One thought is that all sandbox requests require the `type` parameter.  This allows us to better simulate the flow for each financial institution.  Here's a sample successful curl request for submitting a Chase MFA code:

```
curl -X POST https://tartan.plaid.com/auth/step \
  -d client_id=test_id \
  -d secret=test_secret \
  -d access_token=test \
  -d mfa=1234 \
  -d type=chase
```
